Repository SonarSource/rspec, pull requests merged in 2021-11, with the labels that each got.

#555 Modify rule S5869: Add Python as covered language
  rules/S5869/python/metadata.json
  rules/S5869/python/rule.adoc
Labels: python

#563 Modify rule S5856: Add Python as covered language
  rules/S5856/python/metadata.json
  rules/S5856/python/rule.adoc
Labels: python

#265 Create rule S5883[php]: OS commands should not be vulnerable to argument injection attacks
  rules/S5883/description.adoc
  rules/S5883/php/rule.adoc
  rules/S5883/php/see.adoc
Labels: php

#416 Create rule S5843[kotlin]: Regular expressions should not be too complicated
  rules/S5843/compliant.adoc
  rules/S5843/description.adoc
  rules/S5843/exceptions.adoc
  rules/S5843/kotlin/compliant.adoc
  rules/S5843/kotlin/metadata.json
  rules/S5843/kotlin/noncompliant.adoc
  rules/S5843/kotlin/rule.adoc
  rules/S5843/noncompliant.adoc
  rules/S5843/rule.adoc
Labels: kotlin

#422 Create rule S5856[kotlin]: Regular expressions should be syntacticall…
  rules/S5856/highlighting.adoc
  rules/S5856/java/rule.adoc
  rules/S5856/kotlin/metadata.json
  rules/S5856/kotlin/rule.adoc
  rules/S5856/message.adoc
Labels: kotlin

#570 Modify rule S1121: Describe unexpected creation of global variables
  rules/S1121/javascript/rule.adoc
Labels: jsts

#315 Modify rule S5146 - Support Location header
  rules/S5146/csharp/rule.adoc
  rules/S5146/java/rule.adoc
  rules/S5146/javascript/rule.adoc
  rules/S5146/php/rule.adoc
  rules/S5146/python/rule.adoc
Labels: java, security, python, dotnet, php, jsts

#571 Modify S4824: Fix broken link
  rules/S4824/php/rule.adoc
Labels: php

#557 Modify rule S5857: Add Python as covered language
  rules/S5857/python/metadata.json
  rules/S5857/python/rule.adoc
Labels: python

#482 Create rule S4423[cloudformation]: Add AWS Elasticsearch Domain
  rules/S4423/cloudformation/highlighting.adoc
  rules/S4423/cloudformation/metadata.json
  rules/S4423/cloudformation/rule.adoc
Labels: iac

#565 Modify rule S6304: Add exception for KMS key policies to S6304
  rules/S6304/cloudformation/rule.adoc
  rules/S6304/exceptions.adoc
  rules/S6304/terraform/rule.adoc
Labels: iac

#495 Create rule S5332[terraform]: Add AWS Elasticsearch Domain
  rules/S5332/terraform/highlighting.adoc
  rules/S5332/terraform/metadata.json
  rules/S5332/terraform/rule.adoc
Labels: iac

#508 Create rule S5332[terraform]: Add AWS Load Balancer Listeners
  rules/S5332/terraform/highlighting.adoc
  rules/S5332/terraform/rule.adoc
Labels: iac

#498 Create rule S5332[terraform]: Add ECS Task Definition
  rules/S5332/terraform/highlighting.adoc
  rules/S5332/terraform/rule.adoc
Labels: iac

#496 Create rule S5332[cloudformation]: Add AWS Elasticsearch Domain
  rules/S5332/cloudformation/highlighting.adoc
  rules/S5332/cloudformation/metadata.json
  rules/S5332/cloudformation/rule.adoc
Labels: iac

#503 Create rule S5332[terraform]: Add ElastiCache Replication Group
  rules/S5332/terraform/highlighting.adoc
  rules/S5332/terraform/rule.adoc
Labels: iac

#506 Create rule S5332[cloudformation]: Add AWS Load Balancer Listeners
  rules/S5332/cloudformation/highlighting.adoc
  rules/S5332/cloudformation/rule.adoc
Labels: iac

#500 Create rule S5332[terraform]: Add Kinesis Data Streams
  rules/S5332/terraform/highlighting.adoc
  rules/S5332/terraform/rule.adoc
Labels: iac

#502 Create rule S5332[cloudformation]: Add ElastiCache Replication Group
  rules/S5332/cloudformation/highlighting.adoc
  rules/S5332/cloudformation/rule.adoc
Labels: iac

#501 Create rule S5332[cloudformation]: Add kinesis data stream
  rules/S5332/cloudformation/highlighting.adoc
  rules/S5332/cloudformation/rule.adoc
Labels: iac

#553 Create rule S6258[terraform]: Add AWS Load Balancing
  rules/S6258/terraform/rule.adoc
Labels: iac

#549 Create rule S6258[terraform]: Add AWS CloudFront Distributions
  rules/S6258/terraform/rule.adoc
Labels: iac

#544 Create rule S6258[terraform]: Add AWS ElasticSearch Domains
  rules/S6258/terraform/rule.adoc
Labels: iac

#532 Create rule S6258[terraform]: Add AWS Accelerator
  rules/S6258/terraform/rule.adoc
Labels: iac

#531 Create rule S6258[terraform]: Add AWS Redshift Clusters
  rules/S6258/terraform/rule.adoc
Labels: iac

#529 Create rule S6258[terraform]: Add AWS DocDB Clusters
  rules/S6258/terraform/rule.adoc
Labels: iac

#527 Create rule S6258[terraform]: Add AWS MQ Broker
  rules/S6258/terraform/rule.adoc
Labels: iac

#524 Create rule S6258[terraform]: Add AWS MSK
  rules/S6258/terraform/rule.adoc
Labels: iac

#515 Create rule S6258[terraform]: Add AWS API Gateway Stages
  rules/S6258/terraform/rule.adoc
Labels: iac

#554 Create rule S6258[cloudformation]: Add AWS Load Balancing v2
  rules/S6258/cloudformation/rule.adoc
Labels: iac

#550 Create rule S6258[cloudformation]: Add AWS ELB Listeners
  rules/S6258/cloudformation/rule.adoc
Labels: iac

#533 Create rule S6258[cloudformation]: Add AWS ES/OpenSearch Domains
  rules/S6258/cloudformation/rule.adoc
Labels: iac

#528 Create rule S6258[cloudformation]: Add AWS MQ Broker
  rules/S6258/cloudformation/rule.adoc
Labels: iac

#526 Create rule S6258[cloudformation]: Add AWS DocDB Clusters
  rules/S6258/cloudformation/rule.adoc
Labels: iac

#523 Create rule S6258[cloudformation]: Add AWS MSK
  rules/S6258/cloudformation/rule.adoc
Labels: iac

#514 Create rule S6258[cloudformation]: Add AWS API Gateway Stages
  rules/S6258/cloudformation/rule.adoc
Labels: iac

#586 Modify rule S5301: Fix typo in rule description
  rules/S5301/java/rule.adoc
Labels: java

#587 Update CFamily `quickfix` metadata
  rules/S1016/cfamily/metadata.json
  rules/S1044/cfamily/metadata.json
  rules/S1110/metadata.json
  rules/S1155/cfamily/metadata.json
  rules/S1238/cfamily/metadata.json
  rules/S1270/cfamily/metadata.json
  rules/S1709/cfamily/metadata.json
  rules/S1905/cfamily/metadata.json
  rules/S2209/cfamily/metadata.json
  rules/S2234/cfamily/metadata.json
  rules/S2479/cfamily/metadata.json
  rules/S3229/cfamily/metadata.json
  rules/S3471/cfamily/metadata.json
  rules/S3490/cfamily/metadata.json
  rules/S3542/cfamily/metadata.json
  rules/S3543/cfamily/metadata.json
  rules/S3576/cfamily/metadata.json
  rules/S3609/cfamily/metadata.json
  rules/S3659/cfamily/metadata.json
  rules/S3685/cfamily/metadata.json
  rules/S4962/cfamily/metadata.json
  rules/S5350/cfamily/metadata.json
  rules/S5408/cfamily/metadata.json
  rules/S5415/cfamily/metadata.json
  rules/S5416/cfamily/metadata.json
  rules/S5812/cfamily/metadata.json
  rules/S5817/cfamily/metadata.json
  rules/S5820/cfamily/metadata.json
  rules/S5827/cfamily/metadata.json
  rules/S5950/cfamily/metadata.json
  rules/S5951/cfamily/metadata.json
  rules/S5952/cfamily/metadata.json
  rules/S6003/cfamily/metadata.json
  rules/S6013/cfamily/metadata.json
  rules/S6030/cfamily/metadata.json
  rules/S6032/cfamily/metadata.json
  rules/S6033/cfamily/metadata.json
  rules/S6165/cfamily/metadata.json
  rules/S6234/cfamily/metadata.json
  rules/S798/cfamily/metadata.json
  rules/S818/cfamily/metadata.json
  rules/S831/cfamily/metadata.json
  rules/S995/cfamily/metadata.json
Labels: cfamily

#591 Fix S1110 `quickfix` metadata
  rules/S1110/cfamily/metadata.json
  rules/S1110/metadata.json
Labels: cfamily

#468 Modify rule S2119[Java]: the rule now also detect when not assigned locally
  rules/S2119/java/rule.adoc
Labels: java

#593 Modify rule S6308: Fix list in description
  rules/S6308/description.adoc
Labels: iac

#598 Modify rule S6178[cfamily]: add quick fix
  rules/S6178/cfamily/metadata.json
Labels: cfamily

#601 Modify rule S3807: add "setbuffer" function
  rules/S3807/cfamily/rule.adoc
Labels: cfamily

#604 Modify rules S6184 S6192 S6193 S6194[cfamily]: add since-c++20 tag
  rules/S6184/cfamily/metadata.json
  rules/S6192/cfamily/metadata.json
  rules/S6193/cfamily/metadata.json
  rules/S6194/cfamily/metadata.json
  rules/S6194/metadata.json
Labels: cfamily

#609 Modify rule S6184: grammar fixes
  rules/S6184/cfamily/rule.adoc
Labels: cfamily

#613 Modify S1273: Fix broken link
  rules/S1273/cobol/rule.adoc
Labels: cobol

#612 Modify S4502: Fix broken links
  rules/S4502/java/rule.adoc
Labels: java

#614 Modify rule S1144: Add PHP enum example
  rules/S1144/php/rule.adoc
Labels: php

#616 Modify rule S1238[cfamily]: exception for coroutines (CPP-3317)
  rules/S1238/cfamily/rule.adoc
Labels: cfamily

#618 Modify rule S6193: mark quick fix as infeasible
  rules/S6193/cfamily/metadata.json
Labels: cfamily

#619 Modify rule S6184: quickfix is infeasible (CPP-2952)
  rules/S6184/cfamily/metadata.json
Labels: cfamily

#611 Modify rule S6184: grammar fix
  rules/S6184/cfamily/message.adoc
Labels: cfamily

#620 Modify rule S4682,S4454[Java]: add quick fix
  rules/S4454/java/metadata.json
  rules/S4682/java/metadata.json
Labels: java

#605 Modify rule S1763[cfamily]: cover co_return and [[noreturn]]
  rules/S1763/cfamily/rule.adoc
Labels: cfamily

#626 Modify rule S2122[Java/Kotlin]: Change code delimiters
  rules/S2122/description.adoc
Labels: java, kotlin

#630 Remove rules related to the underlying type system of MISRA
  rules/S5351/cfamily/message.adoc
  rules/S5351/cfamily/metadata.json
  rules/S5351/cfamily/rule.adoc
  rules/S5351/metadata.json
  rules/S5352/cfamily/message.adoc
  rules/S5352/cfamily/metadata.json
  rules/S5352/cfamily/rule.adoc
  rules/S5352/metadata.json
  rules/S5354/cfamily/comments-and-links.adoc
  rules/S5354/cfamily/message.adoc
  rules/S5354/cfamily/metadata.json
  rules/S5354/cfamily/rule.adoc
  rules/S5354/metadata.json
  rules/S5355/cfamily/message.adoc
  rules/S5355/cfamily/metadata.json
  rules/S5355/cfamily/rule.adoc
  rules/S5355/metadata.json
  rules/S5451/cfamily/comments-and-links.adoc
  rules/S5451/cfamily/metadata.json
  rules/S5451/cfamily/rule.adoc
  rules/S5451/metadata.json
  rules/S844/cfamily/comments-and-links.adoc
  rules/S844/cfamily/message.adoc
  rules/S844/cfamily/metadata.json
  rules/S844/cfamily/rule.adoc
  rules/S844/metadata.json
  rules/S847/cfamily/comments-and-links.adoc
  rules/S847/cfamily/message.adoc
  rules/S847/cfamily/metadata.json
  rules/S847/cfamily/rule.adoc
  rules/S847/metadata.json
  rules/S848/cfamily/comments-and-links.adoc
  rules/S848/cfamily/message.adoc
  rules/S848/cfamily/metadata.json
  rules/S848/cfamily/rule.adoc
  rules/S848/metadata.json
  rules/S850/cfamily/comments-and-links.adoc
  rules/S850/cfamily/message.adoc
  rules/S850/cfamily/metadata.json
  rules/S850/cfamily/rule.adoc
  rules/S850/metadata.json
  rules/S875/cfamily/comments-and-links.adoc
  rules/S875/cfamily/message.adoc
  rules/S875/cfamily/metadata.json
  rules/S875/cfamily/rule.adoc
  rules/S875/metadata.json
  rules/S944/cfamily/comments-and-links.adoc
  rules/S944/cfamily/message.adoc
  rules/S944/cfamily/metadata.json
  rules/S944/cfamily/rule.adoc
  rules/S944/metadata.json
Labels: cfamily
