Repository SonarSource/rspec, pull requests merged in 2022-02, with the labels that each got.

#768 Fix the file name
  docs/metadata.adoc
Labels: rspec system

#772 Modify rule S6328: Add exceptions for methods throwing an exception
  rules/S5808/java/rule.adoc
Labels: java

#735 RULEAPI-726: Add end-to-end testing
  frontend/src/SearchPage.tsx
  frontend/src/__tests__/EndToEndTesting.test.tsx
  frontend/src/__tests__/SearchPage.test.tsx
  frontend/src/deployment/__tests__/searchIndex.test.ts
  frontend/src/testutils.ts
Labels: rspec system

#777 Reduce amount of debug output in validate_asciidoc.sh
  ci/validate_asciidoc.sh
Labels: rspec system

#776 Fix code smells in index.ts
  frontend/src/deployment/index.ts
Labels: rspec system

#781 Use full clone for tests to enable proper new-code detection on SonarQube
  .cirrus.yml
Labels: rspec system

#783 Quick-fix for frontend testing's bad mock of fs.existsSync
  .cirrus.yml
  frontend/src/deployment/__tests__/pullRequestIndexing.test.ts
Labels: rspec system

#784 Bump memory limit for metadata validation task
  .cirrus.yml
Labels: rspec system

#775 Modify rule S128: Document fall through exception for Java
  rules/S128/java/rule.adoc
Labels: java

#780 While BUILD-1339 problem presists, updating rule coverage manually
  frontend/public/covered_rules.json
Labels: rspec system

#785 Add --detectOpenHandles option to see if it helps investigating flaky frontend_tests
  .cirrus.yml
Labels: rspec system

#655 Modify rule S6329: Turn into generic rule
  rules/S6329/ask-yourself.adoc
  rules/S6329/description.adoc
  rules/S6329/metadata.json
  rules/S6329/recommended.adoc
  rules/S6329/see.adoc
  rules/S6329/terraform/rule.adoc
Labels: iac

#782 Test to accelerate validation
  ci/validate_asciidoc.sh
Labels: rspec system

#770 RULEAPI-633: Autolink RSPECs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/RulePage.tsx
  frontend/src/__tests__/__snapshots__/RulePage.test.tsx.snap
  frontend/src/deployment/__tests__/description.test.ts
  frontend/src/deployment/__tests__/resources/metadata/S1000/cfamily-description.html
  frontend/src/deployment/__tests__/resources/metadata/S1000/default-description.html
  frontend/src/deployment/__tests__/resources/metadata/S1007/cfamily-description.html
  frontend/src/deployment/__tests__/resources/metadata/S1007/default-description.html
  frontend/src/deployment/__tests__/resources/metadata/S3457/cfamily-description.html
  frontend/src/deployment/__tests__/resources/metadata/S3457/csharp-description.html
  frontend/src/deployment/__tests__/resources/metadata/S3457/default-description.html
  frontend/src/deployment/__tests__/resources/metadata/S3457/java-description.html
  frontend/src/deployment/__tests__/resources/metadata/S3457/python-description.html
  frontend/src/deployment/__tests__/resources/metadata/S987/cfamily-description.html
  frontend/src/deployment/__tests__/resources/metadata/S987/default-description.html
  frontend/src/deployment/__tests__/resources/rules/S1000/cfamily/rule.adoc
  frontend/src/deployment/description.ts
Labels: rspec system

#790 Modify rule S6323: Fix exception for PHP
  rules/S6323/php/rule.adoc
Labels: php

#795 Investigate branch fetching
  ci/fetch_branches.sh
Labels: rspec system

#792 Modify rule S107: Update code example for csharp to include rule behavior in the case of constructors.
  rules/S107/csharp/rule.adoc
Labels: dotnet

#732 Modify S2819: update message
  rules/S2819/javascript/message.adoc
Labels: jsts

#759 Modify S2083: Fix compliant code example for csharp rule
  rules/S2083/csharp/rule.adoc
Labels: dotnet

#810 Modify rule S6171: Mark quickfix as covered
  rules/S6171/cfamily/metadata.json
Labels: cfamily

#689 Modify rule S6321: Add GCP examples
  rules/S6321/description.adoc
  rules/S6321/metadata.json
  rules/S6321/see.adoc
  rules/S6321/terraform/metadata.json
  rules/S6321/terraform/rule.adoc
Labels: iac

#813 Define all_required_checks task as the convenient waiting point for update_coverage
  .cirrus.yml
  .github/workflows/update_coverage.yml
Labels: rspec system

#817 Modify S2304 only for CFamily
  rules/S2304/cfamily/metadata.json
  rules/S2304/metadata.json
Labels: cfamily

#818 Modify rule S1155: Add QuickFix C#
  rules/S1155/csharp/metadata.json
Labels: dotnet

#717 Modify Rule S6302: Make generic and add GCP
  rules/S6302/description.adoc
  rules/S6302/metadata.json
  rules/S6302/see.adoc
  rules/S6302/terraform/metadata.json
  rules/S6302/terraform/rule.adoc
Labels: iac

#801 Modify rule S1185: Mark quickfix as covered
  rules/S1185/cfamily/metadata.json
Labels: cfamily

#299 Modify rule S2755[java]: Allow setExpandEntityReferences solution for openJDK >=13
  rules/S2755/java/rule.adoc
Labels: java

#826 Modify rule S4204: Improve rule description
  rules/S4204/javascript/rule.adoc
Labels: jsts

#822 Modify rule S1763: Remove unsupported exceptions
  rules/S1763/javascript/rule.adoc
Labels: jsts

#811 Modify rule S6004: Mark quickfix as partial
  rules/S6004/cfamily/metadata.json
Labels: cfamily

#814 Modify Rule S1314: add quickfix and mention character literals
  rules/S1314/cfamily/metadata.json
  rules/S1314/cfamily/rule.adoc
Labels: cfamily

#829 Modify rule S4601: Improve phrasing
  rules/S4601/java/rule.adoc
Labels: java

#827 Modify rule S1172: Match the behaviour of TypeScript compiler for JS/TS
  rules/S1172/javascript/rule.adoc
Labels: jsts

#809 Update metadata for JS quickfixes
  rules/S1116/javascript/metadata.json
  rules/S113/javascript/metadata.json
  rules/S1131/javascript/metadata.json
  rules/S1264/javascript/metadata.json
  rules/S1438/javascript/metadata.json
  rules/S1441/javascript/metadata.json
  rules/S1488/javascript/metadata.json
  rules/S1537/javascript/metadata.json
  rules/S1940/javascript/metadata.json
  rules/S2427/javascript/metadata.json
  rules/S2933/javascript/metadata.json
  rules/S2966/javascript/metadata.json
  rules/S3257/javascript/metadata.json
  rules/S3353/javascript/metadata.json
  rules/S3498/javascript/metadata.json
  rules/S3504/javascript/metadata.json
  rules/S3512/javascript/metadata.json
  rules/S3812/javascript/metadata.json
  rules/S4023/javascript/metadata.json
  rules/S4156/javascript/metadata.json
  rules/S4157/javascript/metadata.json
  rules/S4204/javascript/metadata.json
  rules/S4325/javascript/metadata.json
Labels: jsts

#722 Modify rule S3735: Ignore JavaScript promises
  rules/S3735/javascript/rule.adoc
Labels: jsts

#830 Modify rule S3317: Consider dot notation in filenames
  rules/S3317/javascript/rule.adoc
Labels: jsts

#832 Modify rule S4328: Clarify what kind of problems could arise
  rules/S4328/javascript/rule.adoc
Labels: jsts

#835 Modify rule S107: Improve C# and VB.NET examples
  rules/S107/csharp/rule.adoc
  rules/S107/vbnet/rule.adoc
Labels: dotnet

#845 Modify rule S6249: update sensitive code samples
  rules/S6249/cloudformation/rule.adoc
  rules/S6249/terraform/rule.adoc
Labels: iac

#848 Modify rule S6011: Provide quickfix information
  rules/S6011/cfamily/metadata.json
Labels: cfamily
