Repository SonarSource/rspec, pull requests merged in 2022-08, with the labels that each got.

#1136 Modify rule S6245: Fix typo
  rules/S6245/javascript/rule.adoc
Labels: jsts

#1133 Modify rule S2076[C#]: Educational content - How to fix it section (APPSEC-55)
  rules/S2076/csharp/how-to-fix-it/dotnet.adoc
Labels: dotnet

#1135 Modify rule S1172: Remove rule from the profile "Sonar way".
  rules/S1172/javascript/metadata.json
Labels: jsts

#1134 Modify rule S1186: Add exception for empty functions.
  rules/S1186/javascript/rule.adoc
Labels: jsts

#1139 Modify rule S3358: Add exception for JSX expressions.
  rules/S3358/javascript/rule.adoc
Labels: jsts

#1140 Modify rule S1186: Add exception for empty functions.
  rules/S1186/javascript/rule.adoc
Labels: jsts

#1141 Modify rule S1116: Add exception paragraph
  rules/S1116/javascript/rule.adoc
Labels: jsts

#1144 Fix javascript code highlighting in javascript rule descriptions.
  rules/S1105/javascript/rule.adoc
  rules/S128/javascript/rule.adoc
  rules/S138/javascript/rule.adoc
  rules/S1440/javascript/rule.adoc
  rules/S1441/javascript/rule.adoc
  rules/S1517/javascript/rule.adoc
  rules/S1535/javascript/rule.adoc
  rules/S1764/javascript/rule.adoc
  rules/S1848/javascript/rule.adoc
  rules/S1854/javascript/rule.adoc
  rules/S2077/javascript/rule.adoc
  rules/S2234/javascript/rule.adoc
  rules/S2583/javascript/rule.adoc
  rules/S2762/javascript/rule.adoc
  rules/S3002/javascript/rule.adoc
  rules/S3003/javascript/rule.adoc
  rules/S3735/javascript/rule.adoc
  rules/S3800/javascript/rule.adoc
  rules/S3923/javascript/rule.adoc
  rules/S4327/javascript/rule.adoc
  rules/S4622/javascript/rule.adoc
  rules/S878/javascript/rule.adoc
  rules/S888/javascript/rule.adoc
  rules/S930/javascript/rule.adoc
Labels: jsts

#1145 Modify rule s3317: Remove rule from the profile "Sonar way".
  rules/S3317/javascript/metadata.json
Labels: jsts

#1151 Modify rule s4144: Add exception for identical functions.
  rules/S4144/javascript/rule.adoc
Labels: jsts

#1158 Java: Fix description of S6244
  rules/S6244/java/rule.adoc
Labels: java

#1163 Add back common rule S1482 and change the status to closed
  rules/S1482/abap/metadata.json
  rules/S1482/abap/rule.adoc
  rules/S1482/cfamily/metadata.json
  rules/S1482/cfamily/rule.adoc
  rules/S1482/cobol/metadata.json
  rules/S1482/cobol/rule.adoc
  rules/S1482/csharp/metadata.json
  rules/S1482/csharp/rule.adoc
  rules/S1482/flex/metadata.json
  rules/S1482/flex/rule.adoc
  rules/S1482/java/metadata.json
  rules/S1482/java/rule.adoc
  rules/S1482/javascript/metadata.json
  rules/S1482/javascript/rule.adoc
  rules/S1482/message.adoc
  rules/S1482/metadata.json
  rules/S1482/parameters.adoc
  rules/S1482/php/metadata.json
  rules/S1482/php/rule.adoc
  rules/S1482/pli/metadata.json
  rules/S1482/pli/rule.adoc
  rules/S1482/plsql/metadata.json
  rules/S1482/plsql/rule.adoc
  rules/S1482/python/metadata.json
  rules/S1482/python/rule.adoc
  rules/S1482/rpg/metadata.json
  rules/S1482/rpg/rule.adoc
  rules/S1482/rule.adoc
  rules/S1482/swift/metadata.json
  rules/S1482/swift/rule.adoc
  rules/S1482/vb6/metadata.json
  rules/S1482/vb6/rule.adoc
  rules/S1482/vbnet/metadata.json
  rules/S1482/vbnet/rule.adoc
Labels: common

#1162 Add back common rule S1483 and change the status to closed
  rules/S1483/abap/metadata.json
  rules/S1483/abap/rule.adoc
  rules/S1483/cfamily/metadata.json
  rules/S1483/cfamily/rule.adoc
  rules/S1483/cobol/metadata.json
  rules/S1483/cobol/rule.adoc
  rules/S1483/comments-and-links.adoc
  rules/S1483/csharp/metadata.json
  rules/S1483/csharp/rule.adoc
  rules/S1483/flex/metadata.json
  rules/S1483/flex/rule.adoc
  rules/S1483/java/metadata.json
  rules/S1483/java/rule.adoc
  rules/S1483/javascript/metadata.json
  rules/S1483/javascript/rule.adoc
  rules/S1483/message.adoc
  rules/S1483/metadata.json
  rules/S1483/parameters.adoc
  rules/S1483/php/metadata.json
  rules/S1483/php/rule.adoc
  rules/S1483/pli/metadata.json
  rules/S1483/pli/rule.adoc
  rules/S1483/plsql/metadata.json
  rules/S1483/plsql/rule.adoc
  rules/S1483/python/metadata.json
  rules/S1483/python/rule.adoc
  rules/S1483/rpg/metadata.json
  rules/S1483/rpg/rule.adoc
  rules/S1483/rule.adoc
  rules/S1483/swift/metadata.json
  rules/S1483/swift/rule.adoc
  rules/S1483/vb6/metadata.json
  rules/S1483/vb6/rule.adoc
  rules/S1483/vbnet/metadata.json
  rules/S1483/vbnet/rule.adoc
Labels: common

#1161 Add back common rule S3424 and change the status to closed
  rules/S3424/abap/metadata.json
  rules/S3424/abap/rule.adoc
  rules/S3424/cfamily/metadata.json
  rules/S3424/cfamily/rule.adoc
  rules/S3424/cobol/metadata.json
  rules/S3424/cobol/rule.adoc
  rules/S3424/csharp/metadata.json
  rules/S3424/csharp/rule.adoc
  rules/S3424/flex/metadata.json
  rules/S3424/flex/rule.adoc
  rules/S3424/java/metadata.json
  rules/S3424/java/rule.adoc
  rules/S3424/javascript/metadata.json
  rules/S3424/javascript/rule.adoc
  rules/S3424/message.adoc
  rules/S3424/metadata.json
  rules/S3424/php/metadata.json
  rules/S3424/php/rule.adoc
  rules/S3424/pli/metadata.json
  rules/S3424/pli/rule.adoc
  rules/S3424/plsql/metadata.json
  rules/S3424/plsql/rule.adoc
  rules/S3424/python/metadata.json
  rules/S3424/python/rule.adoc
  rules/S3424/rpg/metadata.json
  rules/S3424/rpg/rule.adoc
  rules/S3424/rule.adoc
  rules/S3424/swift/metadata.json
  rules/S3424/swift/rule.adoc
  rules/S3424/vbnet/metadata.json
  rules/S3424/vbnet/rule.adoc
Labels: common

#1160 Add back common rule S1484 and change the status to closed
  rules/S1484/abap/metadata.json
  rules/S1484/abap/rule.adoc
  rules/S1484/cfamily/metadata.json
  rules/S1484/cfamily/rule.adoc
  rules/S1484/cobol/metadata.json
  rules/S1484/cobol/rule.adoc
  rules/S1484/csharp/metadata.json
  rules/S1484/csharp/rule.adoc
  rules/S1484/flex/metadata.json
  rules/S1484/flex/rule.adoc
  rules/S1484/html/metadata.json
  rules/S1484/html/rule.adoc
  rules/S1484/java/metadata.json
  rules/S1484/java/rule.adoc
  rules/S1484/javascript/metadata.json
  rules/S1484/javascript/rule.adoc
  rules/S1484/message.adoc
  rules/S1484/metadata.json
  rules/S1484/parameters.adoc
  rules/S1484/php/metadata.json
  rules/S1484/php/rule.adoc
  rules/S1484/pli/metadata.json
  rules/S1484/pli/rule.adoc
  rules/S1484/plsql/metadata.json
  rules/S1484/plsql/rule.adoc
  rules/S1484/python/metadata.json
  rules/S1484/python/rule.adoc
  rules/S1484/rpg/metadata.json
  rules/S1484/rpg/rule.adoc
  rules/S1484/rule.adoc
  rules/S1484/swift/metadata.json
  rules/S1484/swift/rule.adoc
  rules/S1484/tsql/metadata.json
  rules/S1484/tsql/rule.adoc
  rules/S1484/vb6/metadata.json
  rules/S1484/vb6/rule.adoc
  rules/S1484/vbnet/metadata.json
  rules/S1484/vbnet/rule.adoc
  rules/S1484/xml/metadata.json
  rules/S1484/xml/rule.adoc
Labels: common

#1159 Add back common rule S1477 and change the status to closed
  rules/S1477/abap/metadata.json
  rules/S1477/abap/rule.adoc
  rules/S1477/cfamily/metadata.json
  rules/S1477/cfamily/rule.adoc
  rules/S1477/cobol/metadata.json
  rules/S1477/cobol/rule.adoc
  rules/S1477/csharp/metadata.json
  rules/S1477/csharp/rule.adoc
  rules/S1477/flex/metadata.json
  rules/S1477/flex/rule.adoc
  rules/S1477/java/metadata.json
  rules/S1477/java/rule.adoc
  rules/S1477/javascript/metadata.json
  rules/S1477/javascript/rule.adoc
  rules/S1477/message.adoc
  rules/S1477/metadata.json
  rules/S1477/php/metadata.json
  rules/S1477/php/rule.adoc
  rules/S1477/pli/metadata.json
  rules/S1477/pli/rule.adoc
  rules/S1477/plsql/metadata.json
  rules/S1477/plsql/rule.adoc
  rules/S1477/python/metadata.json
  rules/S1477/python/rule.adoc
  rules/S1477/rpg/metadata.json
  rules/S1477/rpg/rule.adoc
  rules/S1477/rule.adoc
  rules/S1477/swift/metadata.json
  rules/S1477/swift/rule.adoc
  rules/S1477/vb6/metadata.json
  rules/S1477/vb6/rule.adoc
  rules/S1477/vbnet/metadata.json
  rules/S1477/vbnet/rule.adoc
Labels: common

#1164 Add back common rule S1606 and change the status to closed
  rules/S1606/abap/metadata.json
  rules/S1606/abap/rule.adoc
  rules/S1606/cfamily/metadata.json
  rules/S1606/cfamily/rule.adoc
  rules/S1606/cobol/metadata.json
  rules/S1606/cobol/rule.adoc
  rules/S1606/csharp/metadata.json
  rules/S1606/csharp/rule.adoc
  rules/S1606/flex/metadata.json
  rules/S1606/flex/rule.adoc
  rules/S1606/java/metadata.json
  rules/S1606/java/rule.adoc
  rules/S1606/javascript/metadata.json
  rules/S1606/javascript/rule.adoc
  rules/S1606/message.adoc
  rules/S1606/metadata.json
  rules/S1606/php/metadata.json
  rules/S1606/php/rule.adoc
  rules/S1606/pli/metadata.json
  rules/S1606/pli/rule.adoc
  rules/S1606/plsql/metadata.json
  rules/S1606/plsql/rule.adoc
  rules/S1606/python/metadata.json
  rules/S1606/python/rule.adoc
  rules/S1606/rpg/metadata.json
  rules/S1606/rpg/rule.adoc
  rules/S1606/rule.adoc
  rules/S1606/swift/metadata.json
  rules/S1606/swift/rule.adoc
  rules/S1606/vb6/metadata.json
  rules/S1606/vb6/rule.adoc
  rules/S1606/vbnet/metadata.json
  rules/S1606/vbnet/rule.adoc
Labels: common

#1166 S3135 Fix typo in the compliant example
  rules/S3135/cfamily/rule.adoc
Labels: cfamily

#1165 Modify rule S5899: Add python as covered language
  rules/S5899/python/highlighting.adoc
  rules/S5899/python/message.adoc
  rules/S5899/python/metadata.json
  rules/S5899/python/rule.adoc
Labels: python
