Repository SonarSource/rspec, pull requests merged in 2022-01, with the labels that each got.

#676 Modify rule S3442 [csharp]: Improve rule description
  rules/S3442/csharp/rule.adoc
Labels: dotnet

#677 SONARJAVA-3770 Modify rule S6217[java]: Update description
  rules/S6217/java/highlighting.adoc
  rules/S6217/java/message.adoc
  rules/S6217/java/metadata.json
  rules/S6217/java/rule.adoc
Labels: java

#678 Modify rule S6387: Add newline
  rules/S6387/description.adoc
Labels: iac

#481 Create rule S4423[terraform]: Add AWS Elasticsearch Domain
  rules/S4423/terraform/highlighting.adoc
  rules/S4423/terraform/rule.adoc
Labels: iac

#679 Modify rule S6387: improved message
  rules/S6378/message.adoc
Labels: iac

#696 Fix the frontend warnings
  frontend/src/RulePage.tsx
Labels: rspec system

#699 Fix python issues raised by SQ for the old code
  rspec-tools/rspec_tools/checklinks.py
  rspec-tools/rspec_tools/coverage.py
  rspec-tools/rspec_tools/create_rule.py
  rspec-tools/rspec_tools/utils.py
  rspec-tools/rspec_tools/validation/description.py
Labels: rspec system

#695 RULEAPI-635: Document testing process
  README.adoc
  docs/testing.adoc
Labels: rspec system

#682 SONARJAVA-4055 Modify rule S4544 [java] Document new interface support
  rules/S4544/java/rule.adoc
Labels: java

#705 RULEAPI-680: Remove the mention of [label]
  README.adoc
  rspec-tools/rspec_tools/create_rule.py
  rspec-tools/tests/test_create_rule.py
Labels: rspec system

#708 Fix UI warnings: <div> nested in <p> and list items lacking keys
  frontend/src/SearchHit.tsx
  frontend/src/SearchPage.tsx
Labels: rspec system

#706 RULEAPI-722: Always cleanup temprary branch for coverage
  .github/workflows/update_coverage.yml
Labels: rspec system

#711 RULEAPI-711: Adjust for underscore in CLOUDFORMATION inside sonar-iac sonarpedia
  rspec-tools/rspec_tools/coverage.py
Labels: rspec system

#715 RULEAPI-703: Fix warnings emitted during `npm run predeploy`
  frontend/src/RulePage.tsx
  frontend/src/deployment/__tests__/description.test.ts
  frontend/src/deployment/description.ts
Labels: rspec system

#709 RULEAPI-571: test the UI components
  frontend/src/RulePage.tsx
  frontend/src/__tests__/App.test.tsx
  frontend/src/__tests__/RulePage.test.tsx
  frontend/src/__tests__/SearchPage.test.tsx
  frontend/src/__tests__/__snapshots__/RulePage.test.tsx.snap
  frontend/src/__tests__/__snapshots__/SearchPage.test.tsx.snap
  frontend/src/deployment/__tests__/resources/plugin_rules/S3457/csharp-metadata.json
  frontend/src/testutils.ts
  frontend/src/utils/__tests__/useRuleCoverage.test.ts
  frontend/src/utils/useRuleCoverage.ts
Labels: rspec system

#716 Fix the snapshot-test failure resulted from the merge
  frontend/src/__tests__/__snapshots__/RulePage.test.tsx.snap
Labels: rspec system

#694 Modify rule S109 for C#: new exceptions
  rules/S109/csharp/rule.adoc
Labels: dotnet

#714 Rename 'Common' to 'Text'
  frontend/src/RulePage.tsx
  frontend/src/utils/useRuleCoverage.ts
  rspec-tools/rspec_tools/utils.py
  rules/S6389/text/metadata.json
  rules/S6389/text/rule.adoc
  supported_languages.adoc
Labels: rspec system

#718 Modify rule S2819: Fix typos
  rules/S2819/javascript/rule.adoc
Labels: javascript

#628 Modify rule S4423: Add cloud tags
  rules/S4423/terraform/metadata.json
Labels: iac

#727 RULEAPI-614: mark unpredictable remediation cost
  rspec-tools/rspec_tools/validation/rule-metadata-schema.json
  rules/S1134/metadata.json
  rules/S1135/metadata.json
  rules/S1239/cfamily/metadata.json
  rules/S124/metadata.json
  rules/S1251/cfamily/metadata.json
  rules/S1256/cfamily/metadata.json
  rules/S1267/cfamily/metadata.json
  rules/S1272/cfamily/metadata.json
  rules/S1489/abap/metadata.json
  rules/S1490/abap/metadata.json
  rules/S1509/abap/metadata.json
  rules/S1681/cobol/metadata.json
  rules/S1914/cfamily/metadata.json
  rules/S2113/java/metadata.json
  rules/S2253/metadata.json
  rules/S2260/cfamily/metadata.json
  rules/S3417/xml/metadata.json
  rules/S3546/java/metadata.json
  rules/S3575/csharp/metadata.json
  rules/S3688/metadata.json
  rules/S3938/cobol/metadata.json
  rules/S4011/java/metadata.json
  rules/S4439/javascript/metadata.json
  rules/S5639/cfamily/metadata.json
  rules/S6212/java/metadata.json
Labels: rspec system

#726 Fix search per language
  frontend/src/SearchHit.tsx
  frontend/src/deployment/__tests__/searchIndex.test.ts
  frontend/src/deployment/searchIndex.ts
  frontend/src/types/IndexStore.ts
Labels: rspec system

#730 Modify rule S5843: Fix JavaScript compliant snippet
  rules/S5843/javascript/rule.adoc
Labels: jsts

#734 Update S2815: it is not deprecated for C++ and not relevant for java and csharp
  rules/S2583/comments-and-links.adoc
  rules/S2815/cfamily/comments-and-links.adoc
  rules/S2815/cfamily/message.adoc
  rules/S2815/cfamily/metadata.json
  rules/S2815/cfamily/rule.adoc
  rules/S2815/csharp/metadata.json
  rules/S2815/csharp/rule.adoc
  rules/S2815/java/metadata.json
  rules/S2815/java/rule.adoc
  rules/S2815/metadata.json
  rules/S2815/rule.adoc
Labels: cfamily

#739 Modify rule S1102: add exception for simple tables
  rules/S1102/html/exceptions.adoc
  rules/S1102/html/rule.adoc
Labels: html

#627 Modify rule S5332: Add cloud tags
  rules/S5332/terraform/metadata.json
Labels: iac

#746 RULEAPI-727: Add interactions tests
  frontend/src/SearchHit.tsx
  frontend/src/SearchPage.tsx
  frontend/src/__tests__/SearchPage.test.tsx
  frontend/src/__tests__/__snapshots__/RulePage.test.tsx.snap
  frontend/src/__tests__/__snapshots__/SearchPage.test.tsx.snap
  frontend/src/deployment/__tests__/resources/metadata/S1000/cfamily-description.html
  frontend/src/deployment/__tests__/resources/metadata/S1000/default-description.html
  frontend/src/deployment/__tests__/resources/metadata/S987/cfamily-description.html
  frontend/src/deployment/__tests__/resources/metadata/S987/default-description.html
  frontend/src/deployment/__tests__/resources/rules/S1000/cfamily/rule.adoc
  frontend/src/deployment/__tests__/resources/rules/S987/cfamily/rule.adoc
  frontend/src/deployment/__tests__/searchIndex.test.ts
  frontend/src/testutils.ts
  frontend/src/utils/routing.ts
Labels: rspec system

#752 Update S1768: it is not deprecated for C++
  rules/S1768/cfamily/metadata.json
  rules/S2583/comments-and-links.adoc
Labels: cfamily

#728 RULEAPI-682: Index multiple types and rules with no languages
  .cirrus.yml
  ci/validate_metadata.sh
  frontend/src/deployment/__tests__/description.test.ts
  frontend/src/deployment/__tests__/metadata.test.ts
  frontend/src/deployment/__tests__/searchIndex.test.ts
  frontend/src/deployment/description.ts
  frontend/src/deployment/metadata.ts
  frontend/src/deployment/searchIndex.ts
  frontend/src/deployment/utils.ts
  frontend/src/types/IndexStore.ts
  frontend/src/utils/useSearch.ts
  rspec-tools/rspec_tools/cli.py
  rspec-tools/rspec_tools/rules.py
  rspec-tools/rspec_tools/validation/metadata.py
  rspec-tools/tests/resources/invalid-rules/S501/metadata.json
  rspec-tools/tests/resources/invalid-rules/S502/metadata.json
  rspec-tools/tests/resources/invalid-rules/S502/scala/metadata.json
  rspec-tools/tests/test_cli.py
  rspec-tools/tests/validation/test_metadata_validation.py
Labels: rspec system

#757 RULEAPI-682: Fix CI failure when no rules have changed
  ci/validate_metadata.sh
Labels: rspec system

#668 Create rule S5147[Java]: NoSQL operations should not be vulnerable to injections
  rules/S5147/description.adoc
  rules/S5147/java/rule.adoc
  rules/S5147/java/see.adoc
  rules/S5147/javascript/rule.adoc
  rules/S5147/php/rule.adoc
  rules/S5147/rule.adoc
Labels: java

#721 RULEAPI-724: Strikethrough rule ID if the rule is closed, deprecated,…
  frontend/src/RulePage.tsx
  frontend/src/SearchHit.tsx
  frontend/src/__tests__/RulePage.test.tsx
  frontend/src/__tests__/SearchPage.test.tsx
  frontend/src/__tests__/__snapshots__/RulePage.test.tsx.snap
  frontend/src/__tests__/__snapshots__/SearchPage.test.tsx.snap
  frontend/src/deployment/__tests__/metadata.test.ts
  frontend/src/deployment/__tests__/resources/metadata/S1007/cfamily-description.html
  frontend/src/deployment/__tests__/resources/metadata/S1007/cfamily-metadata.json
  frontend/src/deployment/__tests__/resources/metadata/S1007/default-description.html
  frontend/src/deployment/__tests__/resources/metadata/S1007/default-metadata.json
  frontend/src/deployment/__tests__/resources/rules/S1007/cfamily/comments-and-links.adoc
  frontend/src/deployment/__tests__/resources/rules/S1007/cfamily/metadata.json
  frontend/src/deployment/__tests__/resources/rules/S1007/cfamily/rule.adoc
  frontend/src/deployment/__tests__/resources/rules/S1007/metadata.json
  frontend/src/deployment/__tests__/searchIndex.test.ts
Labels: rspec system
