Repository SonarSource/rspec, pull requests merged in 2022-11, with the labels that each got.

#1179 Modify rule S1313: Add exceptions for ranges used for documentation purposes
  rules/S1313/kotlin/rule.adoc
Labels: kotlin

#1280 Modify rule S1151 (dotnet): Update doc to reflect implementation
  rules/S1151/csharp/rule.adoc
Labels: dotnet

#1377 Modify rule S6252: Add new Terraform code sample
  rules/S6252/terraform/rule.adoc
Labels: iac

#1378 Modify rule S6258: Add new Terraform code sample
  rules/S6258/terraform/rule.adoc
Labels: iac

#1379 Modify rule S6255: Add new Terraform code sample
  rules/S6255/terraform/rule.adoc
Labels: iac

#1380 Modify rule S6245: Add new Terraform code sample
  rules/S6245/terraform/rule.adoc
Labels: iac

#1385 Modify Rule S5334(Csharp): Fix sample typo
  rules/S5334/csharp/how-to-fix-it/dotnet.adoc
Labels: dotnet

#1052 Modify rule S5542[java]: Detect CBC mode when used with padding (APPSEC-31)
  rules/S5542/description.adoc
  rules/S5542/java/highlighting.adoc
  rules/S5542/java/message.adoc
  rules/S5542/java/rule.adoc
Labels: java

#1384 Modify rule S5147[JS/TS]: Change text to the education framework format (APPSEC-233)
  docs/allowed_framework_names.adoc
  rules/S5147/common/fix/code-rationale.adoc
  rules/S5147/common/fix/plain-string-values.adoc
  rules/S5147/common/pitfalls/code-execution.adoc
  rules/S5147/javascript/how-to-fix-it/mongodb.adoc
  rules/S5147/javascript/how-to-fix-it/mongoose.adoc
  rules/S5147/javascript/metadata.json
  rules/S5147/javascript/rule.adoc
Labels: jsts

#1374 Modify rule S6303: Text improvement suggestion (APPSEC-178)
  rules/S6303/cloudformation/message.adoc
  rules/S6303/cloudformation/rule.adoc
  rules/S6303/description.adoc
  rules/S6303/javascript/rule.adoc
  rules/S6303/metadata.json
  rules/S6303/recommended.adoc
  rules/S6303/terraform/rule.adoc
Labels: iac

#1407 Modify rule S1116: Change RSPEC to match current implementation (CPP-3875)
  rules/S1116/cfamily/rule.adoc
Labels: cfamily

#1417 Deprecate rule S1100
  rules/S1100/html/metadata.json
Labels: html

#344 Update rule S2114: Collections should not be passed as arguments to their own methods
  rules/S2114/kotlin/compliant.adoc
  rules/S2114/kotlin/metadata.json
  rules/S2114/kotlin/noncompliant.adoc
  rules/S2114/kotlin/rule.adoc
Labels: kotlin

#1054 Modify rule S5542[kotlin]: Detect CBC mode when used with padding (APPSEC-30)
  rules/S5542/kotlin/highlighting.adoc
  rules/S5542/kotlin/message.adoc
  rules/S5542/kotlin/rule.adoc
Labels: kotlin

#1431 Modify rule S3456: Raise on ReadOnlySpan.ToArray()
  rules/S3456/csharp/highlighting.adoc
  rules/S3456/csharp/message.adoc
  rules/S3456/csharp/metadata.json
  rules/S3456/csharp/rule.adoc
Labels: dotnet
