Repository SonarSource/rspec, pull requests merged in 2022-03, with the labels that each got.

#852 Modify rules S5019,S3608: Provide quickfix information
  rules/S3608/cfamily/metadata.json
  rules/S5019/cfamily/metadata.json
Labels: cfamily

#761 Modify rule S4423[terraform]:Add SSL policy for Google Cloud load balancers
  rules/S4423/terraform/highlighting.adoc
  rules/S4423/terraform/message.adoc
  rules/S4423/terraform/metadata.json
  rules/S4423/terraform/rule.adoc
Labels: iac

#760 Modify rule S5332[terraform]: add GCP load balancers
  rules/S5332/terraform/highlighting.adoc
  rules/S5332/terraform/rule.adoc
Labels: iac

#733 Modify Rule S6329: Make generic and add GCP
  rules/S6329/metadata.json
  rules/S6329/terraform/metadata.json
  rules/S6329/terraform/rule.adoc
Labels: iac

#860 Modify rule S1135: Add non-compliant code example for python
  rules/S1135/python/rule.adoc
Labels: python

#866 Modify rule S4035 [C#]: Fix documentation
  rules/S4035/csharp/rule.adoc
Labels: dotnet

#851 Modify rule S3453: Fix compliant code example for VBNet
  rules/S3453/vbnet/rule.adoc
Labels: dotnet

#804 Modify rule S6413: Add Google Cloud Logging bucket support
  rules/S6413/ask-yourself.adoc
  rules/S6413/description.adoc
  rules/S6413/highlighting.adoc
  rules/S6413/message.adoc
  rules/S6413/metadata.json
  rules/S6413/recommended.adoc
  rules/S6413/terraform/metadata.json
  rules/S6413/terraform/rule.adoc
Labels: iac

#778 Modify rule S6258[terraform]: Add GCP modules
  rules/S6258/metadata.json
  rules/S6258/terraform/rule.adoc
Labels: iac

#870 Deprecate rule S3400: deprecate rule for CFamily (CPP-3456)
  rules/S3400/cfamily/metadata.json
Labels: cfamily

#796 Fix SonarQube warning about missing reference for analysis
  .cirrus.yml
  ci/fetch_branches.sh
Labels: rspec system

#867 S1988 Delete never implemented duplicated rule
  rules/S1988/cfamily/comments-and-links.adoc
  rules/S1988/cfamily/message.adoc
  rules/S1988/cfamily/metadata.json
  rules/S1988/cfamily/rule.adoc
  rules/S1988/metadata.json
  rules/S2015/php/comments-and-links.adoc
  rules/S2669/cfamily/comments-and-links.adoc
  rules/S836/comments-and-links.adoc
Labels: cfamily

#769 Modify Rule S6006: implement quickfix
  rules/S6006/cfamily/metadata.json
Labels: cfamily

#897 Modify rule S1940: Add code examples for python
  rules/S1940/python/rule.adoc
Labels: python

#895 Modify rule S6383: Add secondary location
  rules/S6385/highlighting.adoc
  rules/S6385/message.adoc
Labels: iac

#869 Modify S4423: Fix messages for Terraform and Cloudformation
  rules/S4423/cloudformation/message.adoc
  rules/S4423/cloudformation/rule.adoc
  rules/S4423/terraform/message.adoc
Labels: iac

#874 Modify rule S5332: Update issue message
  rules/S5332/cloudformation/message.adoc
  rules/S5332/cloudformation/rule.adoc
  rules/S5332/terraform/message.adoc
  rules/S5332/terraform/rule.adoc
Labels: iac

#837 Modify rule S2761: edit title and description for Python
  rules/S2761/python/metadata.json
  rules/S2761/python/rule.adoc
Labels: python

#904 Modify rule S6385: Update highlighting
  rules/S6385/highlighting.adoc
Labels: iac

#876 Modify rule S6378: Update issue message
  rules/S6378/message.adoc
Labels: iac

#892 Modify rule S6330: Update issue message
  rules/S6330/cloudformation/message.adoc
  rules/S6330/cloudformation/rule.adoc
  rules/S6330/terraform/message.adoc
  rules/S6330/terraform/rule.adoc
Labels: iac

#877 Modify rule S6375: Add secondary locations
  rules/S6375/highlighting.adoc
  rules/S6375/message.adoc
  rules/S6375/terraform/rule.adoc
Labels: iac

#881 Modify rule S6255: Update issue message
  rules/S6255/terraform/message.adoc
  rules/S6255/terraform/rule.adoc
Labels: iac

#880 Modify rule S6252: Update message and title
  rules/S6252/ask-yourself.adoc
  rules/S6252/cloudformation/rule.adoc
  rules/S6252/message.adoc
  rules/S6252/metadata.json
  rules/S6252/terraform/rule.adoc
Labels: iac

#886 Modify rule S6303: Update issue message
  rules/S6303/cloudformation/message.adoc
  rules/S6303/cloudformation/rule.adoc
  rules/S6303/terraform/message.adoc
  rules/S6303/terraform/rule.adoc
Labels: iac

#888 Modify rule S6308: Update issue message
  rules/S6308/cloudformation/message.adoc
  rules/S6308/cloudformation/rule.adoc
  rules/S6308/terraform/message.adoc
  rules/S6308/terraform/rule.adoc
Labels: iac

#843 Modify rule S1451: adjust description for Python
  rules/S1451/python/rule.adoc
Labels: python

#882 Modify rule S6270: Update issue message and rule title
  rules/S6270/message.adoc
  rules/S6270/metadata.json
Labels: iac

#907 Modify rule S2761: Add more precise error message and description for python
  rules/S2761/python/rule.adoc
Labels: python

#902 Modify rule S1291: Add non-compliant code for python
  rules/S1291/python/rule.adoc
Labels: python

#840 Modify rule S1172: adjust description for Python
  rules/S1172/python/rule.adoc
Labels: python

#836 Modify rule S3699: adjust description for Python
  rules/S3699/python/rule.adoc
Labels: python

#834 Modify rule S3801: adjust description for Python
  rules/S3801/python/rule.adoc
Labels: python

#794 Modify rule S6353: Add Python as covered language
  rules/S6353/implemtation.adoc
  rules/S6353/php/rule.adoc
  rules/S6353/python/metadata.json
  rules/S6353/python/rule.adoc
Labels: python

#901 Modify rule S3242: fix typo
  rules/S3242/csharp/rule.adoc
Labels: dotnet

#755 Modify Rule S6364: Add Azure
  rules/S6364/highlighting.adoc
  rules/S6364/message.adoc
  rules/S6364/terraform/metadata.json
  rules/S6364/terraform/rule.adoc
Labels: iac

#884 Modify rule S6281: Update issue messages
  rules/S6281/cloudformation/highlighting.adoc
  rules/S6281/cloudformation/message.adoc
  rules/S6281/cloudformation/rule.adoc
  rules/S6281/message.adoc
  rules/S6281/terraform/highlighting.adoc
  rules/S6281/terraform/message.adoc
  rules/S6281/terraform/rule.adoc
Labels: iac

#889 Modify rule S6319: Update issue message
  rules/S6319/cloudformation/message.adoc
  rules/S6319/cloudformation/rule.adoc
  rules/S6319/terraform/message.adoc
  rules/S6319/terraform/rule.adoc
Labels: iac

#890 Modify rule S6327: Update issue message
  rules/S6327/cloudformation/message.adoc
  rules/S6327/cloudformation/rule.adoc
  rules/S6327/terraform/message.adoc
  rules/S6327/terraform/rule.adoc
Labels: iac

#893 Modify rule S6332: Update issue message
  rules/S6332/cloudformation/message.adoc
  rules/S6332/cloudformation/rule.adoc
  rules/S6332/terraform/message.adoc
  rules/S6332/terraform/rule.adoc
Labels: iac

#896 Modify rule S6364: Update issue message
  rules/S6364/message.adoc
Labels: iac

#916 MMF-2707 Bring quick fixes to more JS and TS existing rules
  rules/S108/javascript/metadata.json
  rules/S1110/javascript/metadata.json
  rules/S1126/javascript/metadata.json
  rules/S1128/javascript/metadata.json
  rules/S1172/javascript/metadata.json
  rules/S1186/javascript/metadata.json
  rules/S125/javascript/metadata.json
  rules/S1533/javascript/metadata.json
  rules/S1534/javascript/metadata.json
  rules/S1763/javascript/metadata.json
  rules/S2688/javascript/metadata.json
  rules/S2757/javascript/metadata.json
  rules/S2871/javascript/metadata.json
  rules/S2990/javascript/metadata.json
  rules/S3403/javascript/metadata.json
  rules/S3415/javascript/metadata.json
  rules/S3626/javascript/metadata.json
  rules/S3696/javascript/metadata.json
  rules/S3863/javascript/metadata.json
  rules/S3972/javascript/metadata.json
  rules/S3981/javascript/metadata.json
  rules/S3984/javascript/metadata.json
  rules/S4138/javascript/metadata.json
  rules/S4322/javascript/metadata.json
  rules/S4619/javascript/metadata.json
  rules/S4621/javascript/metadata.json
  rules/S4623/javascript/metadata.json
  rules/S4634/javascript/metadata.json
  rules/S4782/javascript/metadata.json
  rules/S6325/javascript/metadata.json
Labels: jsts

#797 Modify rule S6328: Add Python as covered language
  rules/S6328/implementation.adoc
  rules/S6328/php/rule.adoc
  rules/S6328/python/metadata.json
  rules/S6328/python/rule.adoc
Labels: python

#793 Modify rule S6326: Add Python as supported language
  rules/S6326/implementation.adoc
  rules/S6326/php/rule.adoc
  rules/S6326/python/metadata.json
  rules/S6326/python/rule.adoc
Labels: python

#789 Modify rule S6323: Add Python as covered language
  rules/S6323/implementation.adoc
  rules/S6323/javascript/rule.adoc
  rules/S6323/php/rule.adoc
  rules/S6323/python/metadata.json
  rules/S6323/python/rule.adoc
Labels: python

#816 Modify rule S2190: adjust rule description for Java
  rules/S2190/java/rule.adoc
Labels: java

#831 Modify rule S2222: Add C# and VB.NET to SonarWay
  rules/S2222/csharp/description.adoc
  rules/S2222/csharp/metadata.json
  rules/S2222/vbnet/description.adoc
  rules/S2222/vbnet/metadata.json
Labels: dotnet

#918 Modify rule S6258: Remove GCP tag from CF
  rules/S6258/metadata.json
  rules/S6258/terraform/metadata.json
Labels: iac
