Repository SonarSource/rspec, pull requests merged in 2022-07, with the labels that each got.

#1097 Modify rule S1143: improve the description (no functional change)
  rules/S1143/javascript/rule.adoc
Labels: jsts

#1099 BUILD-1697 enable update_coverage to run cirrus CI checks without human intervention
  .github/workflows/update_coverage.yml
Labels: rspec system

#1092 Modify rule S1534: report on JSX
  rules/S1534/javascript/metadata.json
  rules/S1534/javascript/rule.adoc
Labels: jsts

#1088 Create rule S6245: Add JS as covered language (APPSEC-41)
  rules/S6245/javascript/metadata.json
  rules/S6245/javascript/rule.adoc
Labels: jsts

#1084 Create rule S6265: Add JS as covered language (APPSEC-39)
  rules/S6265/javascript/description.adoc
  rules/S6265/javascript/metadata.json
  rules/S6265/javascript/recommended.adoc
  rules/S6265/javascript/rule.adoc
Labels: jsts

#1083 Modify rule S5838: Polish the rule.adoc
  rules/S5838/java/rule.adoc
Labels: java

#1104 Replace remediation 'mn' with 'min'
  rspec-tools/rspec_tools/validation/rule-metadata-schema.json
  rules/S1008/cfamily/metadata.json
  rules/S1021/cfamily/metadata.json
  rules/S1076/metadata.json
  rules/S110/metadata.json
  rules/S1173/metadata.json
  rules/S1230/metadata.json
  rules/S137/metadata.json
  rules/S1613/php/metadata.json
  rules/S1646/metadata.json
  rules/S1689/cobol/metadata.json
  rules/S1727/cobol/metadata.json
  rules/S1730/metadata.json
  rules/S1748/cobol/metadata.json
  rules/S1847/metadata.json
  rules/S1974/metadata.json
  rules/S2244/abap/metadata.json
  rules/S2662/metadata.json
  rules/S2669/cfamily/metadata.json
  rules/S3955/metadata.json
  rules/S4084/html/metadata.json
  rules/S4517/java/metadata.json
  rules/S4645/html/metadata.json
  rules/S809/cfamily/metadata.json
  rules/S816/cfamily/metadata.json
  rules/S821/cfamily/metadata.json
  rules/S827/cfamily/metadata.json
  rules/S843/cfamily/metadata.json
  rules/S852/cfamily/metadata.json
  rules/S887/cfamily/metadata.json
  rules/S906/cfamily/metadata.json
  rules/S915/cfamily/metadata.json
  rules/S918/metadata.json
  rules/S931/cfamily/metadata.json
Labels: rspec system, common

#1108 Modify rule S4830: fix example code indentation for Kotlin
  rules/S4830/kotlin/rule.adoc
Labels: kotlin

#1063 Modify rule S4225: Add VB.NET
  rules/S4225/comments-and-links.adoc
  rules/S4225/csharp/metadata.json
  rules/S4225/csharp/rule.adoc
  rules/S4225/rspectator.adoc
  rules/S4225/rule.adoc
  rules/S4225/vbnet/metadata.json
  rules/S4225/vbnet/rule.adoc
Labels: dotnet

#1113 Modify rule S6423: Swap arguments in LogError call in compliant solution
  rules/S6423/csharp/rule.adoc
Labels: dotnet

#1121 Modify rule S2083[C#]: Educational content (APPSEC-49)
  docs/allowed_framework_names.adoc
  rules/S2083/common/fix/code-rationale.adoc
  rules/S2083/common/fix/how-does-this-work.adoc
  rules/S2083/csharp/how-to-fix-it/dotnet.adoc
  rules/S2083/csharp/rule.adoc
  rules/S2083/java/how-to-fix-it/java-se.adoc
Labels: dotnet

#1109 Modify Rule S3649: Education Framework (APPSEC-46 & APPSEC-47)
  docs/allowed_framework_names.adoc
  rules/S3649/common/fix/code-rationale.adoc
  rules/S3649/common/fix/prepared-statements.adoc
  rules/S3649/common/images/.gitkeep
  rules/S3649/common/pitfalls/.gitkeep
  rules/S3649/common/resources/articles.adoc
  rules/S3649/common/resources/docs.adoc
  rules/S3649/common/resources/presentations.adoc
  rules/S3649/common/resources/standards.adoc
  rules/S3649/csharp/how-to-fix-it/dapper.adoc
  rules/S3649/csharp/how-to-fix-it/entity-framework.adoc
  rules/S3649/csharp/metadata.json
  rules/S3649/csharp/rule.adoc
  rules/S3649/csharp/see.adoc
  rules/S3649/description.adoc
  rules/S3649/impact.adoc
  rules/S3649/java/how-to-fix-it/hibernate.adoc
  rules/S3649/java/how-to-fix-it/java-se.adoc
  rules/S3649/java/how-to-fix-it/spring-jdbc.adoc
  rules/S3649/java/metadata.json
  rules/S3649/java/rule.adoc
  rules/S3649/java/see.adoc
  rules/S3649/javascript/metadata.json
  rules/S3649/javascript/rule.adoc
  rules/S3649/metadata.json
  rules/S3649/php/metadata.json
  rules/S3649/php/rule.adoc
  rules/S3649/python/metadata.json
  rules/S3649/python/rule.adoc
  rules/S3649/rationale.adoc
Labels: java, dotnet

#1123 Modify rule S1488: Remove Javascript/Typescript from the Sonar way profile
  rules/S1488/javascript/metadata.json
Labels: jsts

#1122 Modify rule S4060: Add VB.NET code snippets
  rules/S4060/csharp/rule.adoc
  rules/S4060/rspectator.adoc
  rules/S4060/rule.adoc
  rules/S4060/vbnet/rule.adoc
Labels: dotnet

#1126 Modify rule S1117: Remove rule for JavaScript/TypeScript from profile Sonar way
  rules/S1117/javascript/metadata.json
Labels: jsts

#1125 Modify rule S3358: Add an exception for JSX expressions.
  rules/S3358/javascript/rule.adoc
Labels: jsts

#1124 Modify rule S1116: Add exception paragraph
  rules/S1116/javascript/rule.adoc
Labels: jsts
