Repository SonarSource/rspec, pull requests merged in 2023-01, with the labels that each got.

#1487 Modify rule S6480: Remove it from the "Sonar way" default profile
  rules/S6480/javascript/metadata.json
Labels: jsts

#1491 Modify rule S1527: Add mention about why we keep adopted future reserved words
  rules/S1527/description.adoc
Labels: jsts

#1484 Modify rule S3628: Raw string literals should be used
  rules/S3628/cfamily/metadata.json
  rules/S3628/cfamily/rule.adoc
Labels: cfamily

#779 Modify Rule S6323: Fix for PHP
  rules/S6323/php/rule.adoc
Labels: php

#1500 Modify S3649(JS): Add Education Framework
  docs/allowed_framework_names.adoc
  rules/S3649/javascript/how-to-fix-it/knex.adoc
  rules/S3649/javascript/how-to-fix-it/sequelize.adoc
  rules/S3649/javascript/metadata.json
  rules/S3649/javascript/rule.adoc
Labels: jsts

#1476 Modify rule S1168: Raise on default and ternaries
  rules/S1168/csharp/description.adoc
  rules/S1168/csharp/rule.adoc
Labels: dotnet

#1516 Remove unused legacy files
  Pipfile
  Pipfile.lock
  index.html
Labels: rspec system

#1499 Modify S2197: Fix whitespace
  rules/S2197/csharp/rule.adoc
Labels: dotnet

#1513 Modify rule S4663: Add support for C# and VB.NET
  rules/S4663/csharp/description.adoc
  rules/S4663/csharp/metadata.json
  rules/S4663/csharp/noncompliant.adoc
  rules/S4663/csharp/rule.adoc
  rules/S4663/vbnet/description.adoc
  rules/S4663/vbnet/metadata.json
  rules/S4663/vbnet/noncompliant.adoc
  rules/S4663/vbnet/rule.adoc
Labels: dotnet

#1526 Modify rules MMF-2854: Update scopes from All to Main
  rules/S6477/javascript/metadata.json
  rules/S6478/javascript/metadata.json
  rules/S6479/javascript/metadata.json
  rules/S6480/javascript/metadata.json
  rules/S6481/javascript/metadata.json
  rules/S6486/javascript/metadata.json
Labels: jsts
