Repository SonarSource/rspec, pull requests merged in 2023-06, with the labels that each got.

#1971 Modify rule S3443: LaYC format
  rules/S3443/csharp/metadata.json
  rules/S3443/csharp/rule.adoc
  rules/S3443/metadata.json
Labels: dotnet, layc

#1985 Modify rule S2970: LaYC format
  docs/header_names/allowed_framework_names.adoc
  rules/S2970/csharp/metadata.json
  rules/S2970/csharp/rule.adoc
Labels: dotnet, layc

#1955 Modify rule S3433: Migrate to new educational format
  rules/S3433/comments-and-links.adoc
  rules/S3433/csharp/metadata.json
  rules/S3433/csharp/rule.adoc
  rules/S3433/rule.adoc
  rules/S3433/swift/metadata.json
  rules/S3433/swift/rule.adoc
Labels: dotnet, swift

#1994 Modify rule S2306: LaYC format
  rules/S2306/csharp/metadata.json
  rules/S2306/csharp/rule.adoc
Labels: dotnet, layc

#2008 SONARJAVA-4482 Modify S1161: Rework `Why is this an issue` section
  rules/S1161/java/rule.adoc
Labels: java

#1988 Modify rule S3875: LaYC format
  rules/S3875/cfamily/metadata.json
  rules/S3875/cfamily/rule.adoc
  rules/S3875/comments-and-links.adoc
  rules/S3875/csharp/metadata.json
  rules/S3875/csharp/rule.adoc
  rules/S3875/highlighting.adoc
  rules/S3875/message.adoc
  rules/S3875/metadata.json
  rules/S3875/rule.adoc
Labels: dotnet, layc

#2012 SONARJAVA-4488 Modify S2129: Rework `Why is this an issue` section
  rules/S2129/java/rule.adoc
Labels: java, layc

#1966 Modify rule S3464: LaYC format
  rules/S3464/csharp/rule.adoc
  rules/S3464/description.adoc
  rules/S3464/metadata.json
  rules/S3464/resources.adoc
  rules/S3464/vbnet/rule.adoc
Labels: dotnet, layc

#2017 SONARJAVA-4488 Modify S2133: Update rule title and formatting
  rules/S2133/java/metadata.json
  rules/S2133/java/rule.adoc
Labels: java, layc

#1997 Modify rule S3889: LAYC format
  rules/S3889/csharp/rule.adoc
  rules/S3889/description.adoc
  rules/S3889/highlighting.adoc
  rules/S3889/metadata.json
  rules/S3889/resources-dotnet.adoc
  rules/S3889/see.adoc
  rules/S3889/vbnet/rule.adoc
  rules/S3889/why-dotnet.adoc
Labels: dotnet, layc

#2015 SONARJAVA-4488 Modify S2130: Add more examples of non-compliant code
  rules/S2130/java/rule.adoc
Labels: java, layc

#1981 Modify rule S2368: LaYC format
  rules/S2368/csharp/exception-code.adoc
  rules/S2368/csharp/intuitive-code.adoc
  rules/S2368/csharp/resources.adoc
  rules/S2368/csharp/rule.adoc
  rules/S2368/csharp/unintuitive-code.adoc
  rules/S2368/description.adoc
  rules/S2368/metadata.json
  rules/S2368/rspecator.adoc
  rules/S2368/vbnet/exception-code.adoc
  rules/S2368/vbnet/intuitive-code.adoc
  rules/S2368/vbnet/resources.adoc
  rules/S2368/vbnet/rule.adoc
  rules/S2368/vbnet/unintuitive-code.adoc
  rules/S2368/why-dotnet.adoc
Labels: dotnet, layc

#2036 Modify rule S4159: LaYC format
  rules/S4159/csharp/metadata.json
  rules/S4159/csharp/rule.adoc
  rules/S4159/description.adoc
  rules/S4159/metadata.json
  rules/S4159/resources.adoc
  rules/S4159/vbnet/metadata.json
  rules/S4159/vbnet/rule.adoc
  rules/S4159/why.adoc
Labels: dotnet, layc

#1965 S1909: Remove C# since the rule is not applicable
  rules/S1909/comments-and-links.adoc
  rules/S1909/csharp/metadata.json
Labels: dotnet

#2032 Modify rule S3060: LaYC format
  rules/S3060/csharp/metadata.json
  rules/S3060/csharp/rule.adoc
Labels: dotnet, layc

#2037 Modify rule S2930: LaYC format
  rules/S2930/csharp/metadata.json
  rules/S2930/csharp/rule.adoc
  rules/S2930/metadata.json
Labels: dotnet, layc

#2025 SONARJAVA-4488 Modify S2140: Rework rule description and examples
  rules/S2140/java/metadata.json
  rules/S2140/java/rule.adoc
Labels: java, layc

#2024 SONARJAVA-4488 Modify S2134: Rewrite title and entire rule to integrate exceptions
  rules/S2134/java/metadata.json
  rules/S2134/java/rule.adoc
Labels: java, layc

#2047 Modify rule S5856: LaYC format
  rules/S5856/csharp/metadata.json
  rules/S5856/csharp/rule.adoc
  rules/S5856/resources-dotnet.adoc
  rules/S5856/vbnet/metadata.json
  rules/S5856/vbnet/rule.adoc
  rules/S5856/why-dotnet.adoc
Labels: dotnet, layc

#2075 Add review checklist
  .github/pull_request_template.md
  README.adoc
  rspec-tools/rspec_tools/create_rule.py
Labels: rspec system

#1976 Modify rule S6232: CPP-3254 Well defined alternatives to union type-punning
  rules/S6232/cfamily/metadata.json
  rules/S6232/cfamily/rule.adoc
Labels: cfamily

#2088 Create tone_guide.adoc
  docs/description.adoc
  docs/styling_guide.adoc
  docs/tone_guide.adoc
Labels: rspec system

#2083 Modify rule S1006: Migrate to new educational format
  rules/S1006/csharp/rule.adoc
Labels: dotnet, layc

#1984 SONARJAVA-4485 Modify rule S1611: Update rule in line with LayC
  rules/S1611/java/metadata.json
  rules/S1611/java/rule.adoc
Labels: java

#2070 SONARJAVA-4485 Modify rule S1948: Update rule in line with LayC
  rules/S1948/java/rule.adoc
Labels: java

#2062 Modify rule S101: LaYC format
  rules/S101/abap/rule.adoc
  rules/S101/apex/rule.adoc
  rules/S101/cfamily/rule.adoc
  rules/S101/compliant.adoc
  rules/S101/csharp/rule.adoc
  rules/S101/description.adoc
  rules/S101/flex/rule.adoc
  rules/S101/go/rule.adoc
  rules/S101/javascript/rule.adoc
  rules/S101/noncompliant.adoc
  rules/S101/python/rule.adoc
  rules/S101/ruby/rule.adoc
  rules/S101/scala/rule.adoc
  rules/S101/vbnet/rule.adoc
Labels: common, layc

#1983 Modify rule S6535: Adapt to LaYC
  rules/S6535/javascript/rule.adoc
Labels: jsts, layc

#2080 Modify rule S2692: LaYC format
  rules/S2692/cfamily/metadata.json
  rules/S2692/comments-and-links.adoc
  rules/S2692/csharp/metadata.json
  rules/S2692/csharp/rule.adoc
  rules/S2692/flex/metadata.json
  rules/S2692/flex/rule.adoc
  rules/S2692/go/metadata.json
  rules/S2692/go/rule.adoc
  rules/S2692/java/rule.adoc
  rules/S2692/javascript/rule.adoc
  rules/S2692/message.adoc
  rules/S2692/php/metadata.json
  rules/S2692/php/rule.adoc
  rules/S2692/python/metadata.json
  rules/S2692/python/rule.adoc
  rules/S2692/resources-dotnet.adoc
  rules/S2692/rspecator.adoc
  rules/S2692/vb6/metadata.json
  rules/S2692/vb6/rule.adoc
  rules/S2692/vbnet/metadata.json
  rules/S2692/vbnet/rule.adoc
Labels: cfamily, java, python, dotnet, php, flex, vb6, javascript, layc, go

#2064 Modify rule S104: LaYC format
  rules/S104/cfamily/metadata.json
  rules/S104/rule.adoc
Labels: common, layc

#2099 Modify S3600: Migrate it to the Learn-As-You-Code
  rules/S3600/csharp/rule.adoc
Labels: dotnet, layc

#2117 Update rule S935(cfamily): fix typo
  rules/S935/cfamily/rule.adoc
Labels: cfamily

#2115 SONARJAVA-4492 Modify S2446 Modify description and code examples
  rules/S2446/java/metadata.json
  rules/S2446/java/rule.adoc
Labels: java, layc

#2085 Modify rule S2365: Migrate to new educational format
  rules/S2365/csharp/metadata.json
  rules/S2365/csharp/rule.adoc
  rules/S2365/rspecator.adoc
  rules/S2365/vbnet/metadata.json
  rules/S2365/vbnet/rule.adoc
  rules/S2365/why-dotnet.adoc
Labels: dotnet, layc

#2071 Modify rule S4524: LaYC format
  rules/S4524/apex/metadata.json
  rules/S4524/cobol/metadata.json
  rules/S4524/cobol/rule.adoc
  rules/S4524/csharp/metadata.json
  rules/S4524/csharp/rule.adoc
  rules/S4524/rpg/metadata.json
  rules/S4524/rpg/rule.adoc
  rules/S4524/rspecator.adoc
Labels: dotnet, cobol, rpg, layc, apex

#2111 Modify rule S3998: Migrate to new educational format
  rules/S3998/csharp/metadata.json
  rules/S3998/csharp/rule.adoc
  rules/S3998/description.adoc
  rules/S3998/resources-dotnet.adoc
  rules/S3998/rspecator.adoc
  rules/S3998/vbnet/metadata.json
  rules/S3998/vbnet/rule.adoc
  rules/S3998/why-dotnet.adoc
Labels: dotnet, layc

#2119 SONARJAVA-4492 Modify S2629: Rework first sentence and code samples
  rules/S2629/java/rule.adoc
Labels: java, layc

#2116 SONARJAVA-4492 Modify S2447: Modify description and code examples
  rules/S2447/java/metadata.json
  rules/S2447/java/rule.adoc
Labels: java, layc

#2009 Modify rule S6522: Adapt to LaYC
  rules/S6522/javascript/metadata.json
  rules/S6522/javascript/rule.adoc
Labels: jsts, layc

#2125 S2306: Fix some whitespace
  rules/S2306/csharp/rule.adoc
Labels: dotnet, layc

#2109 Modify rule S1699: LaYC format
  rules/S1699/cfamily/rule.adoc
  rules/S1699/csharp/metadata.json
  rules/S1699/csharp/rule.adoc
  rules/S1699/description.adoc
  rules/S1699/java/rule.adoc
  rules/S1699/message.adoc
  rules/S1699/noncompliant.adoc
  rules/S1699/php/metadata.json
  rules/S1699/php/rule.adoc
  rules/S1699/python/metadata.json
  rules/S1699/python/rule.adoc
  rules/S1699/rspecator.adoc
  rules/S1699/rule.adoc
  rules/S1699/vbnet/metadata.json
  rules/S1699/vbnet/rule.adoc
Labels: java, python, dotnet, php, layc

#2089 Modify rule S3218: LaYC format
  rules/S3218/csharp/metadata.json
  rules/S3218/csharp/rule.adoc
  rules/S3218/java/rule.adoc
  rules/S3218/message.adoc
  rules/S3218/rspecator.adoc
  rules/S3218/rule.adoc
  rules/S3218/why.adoc
Labels: dotnet, layc

#2007 Modify rule S6523: Adapt to LaYC
  rules/S6523/javascript/metadata.json
  rules/S6523/javascript/rule.adoc
Labels: jsts, layc

#2132 Modify S2068: Fix Typo
  rules/S2068/java/rule.adoc
Labels: java

#2095 Modify rule S1186: LaYC format
  rules/S1186/csharp/comment-code.adoc
  rules/S1186/csharp/empty-code.adoc
  rules/S1186/csharp/notimplemented-code.adoc
  rules/S1186/csharp/notsupported-code.adoc
  rules/S1186/csharp/rule.adoc
  rules/S1186/vb6/comment-code.adoc
  rules/S1186/vb6/empty-code.adoc
  rules/S1186/vb6/notimplemented-code.adoc
  rules/S1186/vb6/notsupported-code.adoc
  rules/S1186/vb6/rule.adoc
  rules/S1186/vbnet/comment-code.adoc
  rules/S1186/vbnet/empty-code.adoc
  rules/S1186/vbnet/notimplemented-code.adoc
  rules/S1186/vbnet/notsupported-code.adoc
  rules/S1186/vbnet/rule.adoc
  rules/S1186/why-dotnet.adoc
Labels: dotnet, vb6, layc

#2114 Modify rule S927: LaYC format
  rules/S927/cfamily/metadata.json
  rules/S927/cfamily/rule.adoc
  rules/S927/comments-and-links.adoc
  rules/S927/csharp/compliant-code.adoc
  rules/S927/csharp/metadata.json
  rules/S927/csharp/noncompliant-code.adoc
  rules/S927/csharp/rule.adoc
  rules/S927/java/metadata.json
  rules/S927/java/rule.adoc
  rules/S927/javascript/metadata.json
  rules/S927/javascript/rule.adoc
  rules/S927/message.adoc
  rules/S927/rspecator-dotnet.adoc
  rules/S927/vbnet/compliant-code.adoc
  rules/S927/vbnet/metadata.json
  rules/S927/vbnet/noncompliant-code.adoc
  rules/S927/vbnet/rule.adoc
  rules/S927/why-dotnet.adoc
Labels: cfamily, java, dotnet, javascript, layc

#2139 Update expressjs.adoc
  rules/S5131/javascript/how-to-fix-it/expressjs.adoc
Labels: appsec, jsts

#2129 S3904: Migrate to layc level 2
  rules/S3904/csharp/metadata.json
  rules/S3904/csharp/rule.adoc
  rules/S3904/description.adoc
  rules/S3904/highlighting.adoc
  rules/S3904/message.adoc
  rules/S3904/metadata.json
  rules/S3904/resources.adoc
  rules/S3904/rspecator.adoc
  rules/S3904/see.adoc
  rules/S3904/vbnet/metadata.json
  rules/S3904/vbnet/rule.adoc
  rules/S3904/why.adoc
Labels: dotnet, layc

#2091 Modify rule S1163: LaYC format
  rules/S1163/cfamily/rule.adoc
  rules/S1163/comments-and-links.adoc
  rules/S1163/compliant.adoc
  rules/S1163/csharp/rule.adoc
  rules/S1163/description.adoc
  rules/S1163/flex/metadata.json
  rules/S1163/flex/rule.adoc
  rules/S1163/java/rule.adoc
  rules/S1163/javascript/metadata.json
  rules/S1163/javascript/rule.adoc
  rules/S1163/message.adoc
  rules/S1163/metadata.json
  rules/S1163/noncompliant.adoc
  rules/S1163/php/metadata.json
  rules/S1163/php/rule.adoc
  rules/S1163/python/metadata.json
  rules/S1163/python/rule.adoc
  rules/S1163/resources-dotnet.adoc
  rules/S1163/rspecator.adoc
  rules/S1163/rule.adoc
  rules/S1163/vbnet/rule.adoc
  rules/S1163/why.adoc
Labels: cfamily, java, python, dotnet, php, flex, javascript, layc

#2104 Modify rule S3451: LaYC format
  rules/S3451/csharp/rule.adoc
  rules/S3451/rspecator.adoc
Labels: dotnet, layc

#2148 Add a checkbox for the PR title guidelines
  .github/pull_request_template.md
Labels: rspec system

#2138 Modify rule S3871: Update to LaYC
  rules/S3871/csharp/rule.adoc
  rules/S3871/exceptions.adoc
  rules/S3871/metadata.json
  rules/S3871/resources-dotnet.adoc
  rules/S3871/see.adoc
  rules/S3871/vbnet/rule.adoc
  rules/S3871/why-dotnet.adoc
Labels: dotnet, layc

#2128 Modify rule S1215: LaYC format
  rules/S1215/csharp/metadata.json
  rules/S1215/csharp/rspecator.adoc
  rules/S1215/csharp/rule.adoc
Labels: dotnet, layc

#2131 Modify rule S1944: LaYC format
  rules/S1944/abap/metadata.json
  rules/S1944/comments-and-links.adoc
  rules/S1944/csharp/metadata.json
  rules/S1944/csharp/rule.adoc
  rules/S1944/flex/metadata.json
  rules/S1944/flex/rule.adoc
  rules/S1944/javascript/metadata.json
  rules/S1944/javascript/rule.adoc
  rules/S1944/message-dotnet.adoc
  rules/S1944/php/metadata.json
  rules/S1944/php/rule.adoc
  rules/S1944/python/metadata.json
  rules/S1944/python/rule.adoc
  rules/S1944/rspecator-dotnet.adoc
  rules/S1944/rule.adoc
  rules/S1944/see.adoc
  rules/S1944/vbnet/metadata.json
  rules/S1944/vbnet/rule.adoc
Labels: python, dotnet, abap, flex, javascript, layc

#2159 Modify rule S2437: fix VB.NET links and rspecator
  rules/S2437/csharp/rule.adoc
  rules/S2437/java/rule.adoc
  rules/S2437/rspecator.adoc
  rules/S2437/vbnet/rule.adoc
Labels: java, dotnet, layc

#2157 Modify rule S3451: fix non-compliant block
  rules/S3451/csharp/rule.adoc
Labels: dotnet, layc

#2158 Modify rule S2692: fix non-compliant code example
  rules/S2692/csharp/rule.adoc
  rules/S2692/vbnet/rule.adoc
Labels: dotnet, layc

#2162 Deprecate rule S1114
  rules/S1114/java/metadata.json
Labels: java

#2150 Modify rule S3265: LaYC format
  rules/S3265/csharp/rule.adoc
  rules/S3265/rspecator.adoc
Labels: dotnet, layc

#2164 Modify rule S3464: fix grammar, links, resources, rspecator
  rules/S3464/csharp/rule.adoc
  rules/S3464/rspecator.adoc
  rules/S3464/vbnet/rule.adoc
Labels: dotnet, layc

#2153 Modify rule S1472: Adapt to LaYC
  rules/S1472/javascript/rule.adoc
Labels: jsts, layc

#2143 Modify rule S4635: Improve code example
  rules/S4635/csharp/metadata.json
  rules/S4635/csharp/rule.adoc
Labels: dotnet, layc

#2172 Modify rule S2234: LaYC format
  rules/S2234/csharp/compliantCode.adoc
  rules/S2234/csharp/metadata.json
  rules/S2234/csharp/noncompliantCode.adoc
  rules/S2234/csharp/rule.adoc
  rules/S2234/rspectator.adoc
  rules/S2234/vbnet/compliantCode.adoc
  rules/S2234/vbnet/metadata.json
  rules/S2234/vbnet/noncompliantCode.adoc
  rules/S2234/vbnet/rule.adoc
  rules/S2234/why-dotnet.adoc
Labels: dotnet, layc

#2165 Modify rule S100: fix LaYC for Java and JS/TS
  rules/S100/java/rule.adoc
  rules/S100/javascript/rule.adoc
Labels: common, layc

#2146 Modify rule S110: LaYC format
  rules/S110/cfamily/rule.adoc
  rules/S110/csharp/rule.adoc
  rules/S110/java/rule.adoc
  rules/S110/php/rule.adoc
  rules/S110/resources.adoc
  rules/S110/rule.adoc
Labels: common, layc

#2175 Modify rule S3217: Adapt to LaYC
  rules/S3217/csharp/rule.adoc
Labels: dotnet, layc

#2154 Modify Rule S3011: LaYC reflection
  rules/S3011/csharp/rule.adoc
  rules/S3011/description.adoc
  rules/S3011/java/rule.adoc
  rules/S3011/php/rule.adoc
  rules/S3011/resources.adoc
  rules/S3011/ruby/metadata.json
  rules/S3011/ruby/rule.adoc
  rules/S3011/rule.adoc
  rules/S3011/vbnet/rule.adoc
Labels: common

#2186 Fix the preview page deployment: require write access for the action
  .github/workflows/main.yml
Labels: rspec system

#2183 Modify rule S1144: LaYC format
  rules/S1144/csharp/rspecator.adoc
  rules/S1144/csharp/rule.adoc
Labels: dotnet, layc

#2189 Modify rule S1134: Update to LaYC
  rules/S1134/abap/metadata.json
  rules/S1134/abap/rule.adoc
  rules/S1134/apex/non-compliant-example.adoc
  rules/S1134/apex/rule.adoc
  rules/S1134/cfamily/non-compliant-example.adoc
  rules/S1134/cfamily/rule.adoc
  rules/S1134/cobol/non-compliant-example.adoc
  rules/S1134/cobol/rule.adoc
  rules/S1134/comments-and-links.adoc
  rules/S1134/csharp/non-compliant-example.adoc
  rules/S1134/csharp/rule.adoc
  rules/S1134/description.adoc
  rules/S1134/flex/metadata.json
  rules/S1134/flex/rule.adoc
  rules/S1134/go/non-compliant-example.adoc
  rules/S1134/go/rule.adoc
  rules/S1134/html/non-compliant-example.adoc
  rules/S1134/html/rule.adoc
  rules/S1134/java/non-compliant-example.adoc
  rules/S1134/java/rule.adoc
  rules/S1134/javascript/non-compliant-example.adoc
  rules/S1134/javascript/rule.adoc
  rules/S1134/kotlin/non-compliant-example.adoc
  rules/S1134/kotlin/rule.adoc
  rules/S1134/message.adoc
  rules/S1134/metadata.json
  rules/S1134/php/non-compliant-example.adoc
  rules/S1134/php/rule.adoc
  rules/S1134/pli/metadata.json
  rules/S1134/pli/rule.adoc
  rules/S1134/plsql/non-compliant-example.adoc
  rules/S1134/plsql/rule.adoc
  rules/S1134/python/non-compliant-example.adoc
  rules/S1134/python/rule.adoc
  rules/S1134/resources.adoc
  rules/S1134/rpg/metadata.json
  rules/S1134/rpg/rule.adoc
  rules/S1134/rspecator.adoc
  rules/S1134/ruby/non-compliant-example.adoc
  rules/S1134/ruby/rule.adoc
  rules/S1134/rule.adoc
  rules/S1134/scala/non-compliant-example.adoc
  rules/S1134/scala/rule.adoc
  rules/S1134/see.adoc
  rules/S1134/swift/non-compliant-example.adoc
  rules/S1134/swift/rule.adoc
  rules/S1134/tsql/non-compliant-example.adoc
  rules/S1134/tsql/rule.adoc
  rules/S1134/vb6/non-compliant-example.adoc
  rules/S1134/vb6/rule.adoc
  rules/S1134/vbnet/non-compliant-example.adoc
  rules/S1134/vbnet/rule.adoc
  rules/S1134/xml/non-compliant-example.adoc
  rules/S1134/xml/rule.adoc
Labels: cfamily, java, python, dotnet, php, kotlin, abap, cobol, flex, html, pli, plsql, rpg, swift, tsql, xml, vb6, javascript, go, apex

#2168 Modify rule S4275: LaYC format
  rules/S4275/csharp/rule.adoc
  rules/S4275/metadata.json
  rules/S4275/vbnet/metadata.json
  rules/S4275/vbnet/rule.adoc
Labels: dotnet, layc

#2151 Modify rule S3445: LaYC format
  rules/S3445/csharp/rule.adoc
  rules/S3445/rspecator.adoc
Labels: dotnet, layc

#2177 Modify rule S4277: Update to LaYC
  rules/S4277/csharp/rule.adoc
  rules/S4277/description.adoc
  rules/S4277/highlighting.adoc
  rules/S4277/message.adoc
  rules/S4277/metadata.json
  rules/S4277/resources-dotnet.adoc
  rules/S4277/rspecator.adoc
  rules/S4277/vbnet/rule.adoc
  rules/S4277/why-dotnet.adoc
Labels: dotnet, layc

#2185 Modify rule S4583: Update to LaYC
  rules/S4583/csharp/rule.adoc
  rules/S4583/description.adoc
  rules/S4583/highlighting.adoc
  rules/S4583/message.adoc
  rules/S4583/metadata.json
  rules/S4583/resources-dotnet.adoc
  rules/S4583/rspecator.adoc
  rules/S4583/see.adoc
  rules/S4583/vbnet/rule.adoc
  rules/S4583/why-dotnet.adoc
Labels: dotnet, layc

#2178 Modify rule S2290: Update to LaYC
  rules/S2290/csharp/rule.adoc
  rules/S2290/rspecator.adoc
Labels: dotnet, layc

#2199 Modify rule S3464: fix code example
  rules/S3464/csharp/rule.adoc
  rules/S3464/vbnet/rule.adoc
Labels: dotnet, layc

#2201 Modify rule S2692: align C# and VB.NET examples
  rules/S2692/vbnet/rule.adoc
Labels: dotnet, layc

#2167 Modify rule S2137: Adapt to LaYC
  rules/S2137/javascript/rule.adoc
Labels: jsts, layc

#2169 Modify rule S2291: LAYC format
  rules/S2291/csharp/metadata.json
  rules/S2291/csharp/rule.adoc
  rules/S2291/rspecator.adoc
Labels: dotnet, layc

#2160 Modify rule S121: LaYC format
  rules/S121/cfamily/metadata.json
  rules/S121/cfamily/rule.adoc
  rules/S121/common/compliant.adoc
  rules/S121/common/noncompliant.adoc
  rules/S121/csharp/compliant.adoc
  rules/S121/csharp/noncompliant.adoc
  rules/S121/csharp/rule.adoc
  rules/S121/description.adoc
  rules/S121/java/metadata.json
  rules/S121/java/rule.adoc
  rules/S121/javascript/metadata.json
  rules/S121/kotlin/rule.adoc
  rules/S121/noncompliant.adoc
  rules/S121/pli/metadata.json
  rules/S121/pli/rule.adoc
  rules/S121/rule.adoc
  rules/S121/tsql/rule.adoc
Labels: common, layc

#2155 Modify rule S4586: LaYC format
  rules/S4586/csharp/rule.adoc
  rules/S4586/highlighting.adoc
  rules/S4586/message.adoc
  rules/S4586/resources.adoc
  rules/S4586/rspecator.adoc
  rules/S4586/vbnet/rule.adoc
  rules/S4586/why-dotnet.adoc
Labels: dotnet, layc

#2205 Modify S1479: LAYC format
  rules/S1479/csharp/metadata.json
  rules/S1479/csharp/rule.adoc
  rules/S1479/resources-dotnet.adoc
  rules/S1479/rspecator-dotnet.adoc
  rules/S1479/vbnet/metadata.json
  rules/S1479/vbnet/rule.adoc
Labels: dotnet, layc

#2208 Modify S4158: LayC format
  rules/S4158/csharp/metadata.json
  rules/S4158/csharp/rule.adoc
  rules/S4158/highlighting.adoc
  rules/S4158/javascript/rule.adoc
  rules/S4158/message.adoc
  rules/S4158/rspecator.adoc
  rules/S4158/vbnet/metadata.json
  rules/S4158/vbnet/rule.adoc
  rules/S4158/why-dotnet.adoc
Labels: dotnet, layc

#2188 Modify Rule S2757: LaYC =+
  rules/S2757/apex/code-example.adoc
  rules/S2757/apex/fix.adoc
  rules/S2757/apex/rule.adoc
  rules/S2757/cfamily/rule.adoc
  rules/S2757/common/code-example.adoc
  rules/S2757/common/fix.adoc
  rules/S2757/compliant.adoc
  rules/S2757/description.adoc
  rules/S2757/go/code-example.adoc
  rules/S2757/go/fix.adoc
  rules/S2757/go/rule.adoc
  rules/S2757/javascript/code-example.adoc
  rules/S2757/javascript/fix.adoc
  rules/S2757/javascript/rule.adoc
  rules/S2757/kotlin/code-example.adoc
  rules/S2757/kotlin/fix.adoc
  rules/S2757/kotlin/rule.adoc
  rules/S2757/metadata.json
  rules/S2757/noncompliant.adoc
  rules/S2757/php/code-example.adoc
  rules/S2757/php/fix.adoc
  rules/S2757/php/rule.adoc
  rules/S2757/python/rule.adoc
  rules/S2757/ruby/code-example.adoc
  rules/S2757/ruby/fix.adoc
  rules/S2757/ruby/rule.adoc
  rules/S2757/rule.adoc
  rules/S2757/vbnet/rule.adoc
Labels: common

#2195 Modify rule S2589: LaYC format
  rules/S2589/csharp/rule.adoc
Labels: dotnet, layc

#2210 Modify S3966: Fix broken argument
  rules/S3966/csharp/rule.adoc
  rules/S3966/vbnet/rule.adoc
  rules/S3966/why.adoc
Labels: dotnet

#2213 Modify rule S108: fix Kotlin LaYC format
  rules/S108/kotlin/rule.adoc
Labels: layc

#2212 Modify rule S3464: fix VB.NET code example
  rules/S3464/vbnet/rule.adoc
Labels: dotnet, layc

#2214 Modify rule S1110: fix Update dotnet part of the rule to LayC
  rules/S1110/abap/rule.adoc
  rules/S1110/apex/rule.adoc
  rules/S1110/cfamily/rule.adoc
  rules/S1110/cobol/rule.adoc
  rules/S1110/csharp/rule.adoc
  rules/S1110/go/rule.adoc
  rules/S1110/java/rule.adoc
  rules/S1110/javascript/rule.adoc
  rules/S1110/kotlin/rule.adoc
  rules/S1110/php/rule.adoc
  rules/S1110/plsql/rule.adoc
  rules/S1110/python/rule.adoc
  rules/S1110/rspecator.adoc
  rules/S1110/ruby/rule.adoc
  rules/S1110/scala/rule.adoc
  rules/S1110/swift/rule.adoc
  rules/S1110/tsql/rule.adoc
  rules/S1110/vbnet/metadata.json
  rules/S1110/vbnet/rule.adoc
Labels: dotnet, layc

#2222 Modify rule S4277: Fix vbnet diff tag
  rules/S4277/vbnet/rule.adoc
Labels: dotnet, layc

#2221 Modify rule S2445: Fix java diff tag
  rules/S2445/java/rule.adoc
Labels: java

#2156 Modify rule S2198: LaYC format
  rules/S2198/csharp/metadata.json
  rules/S2198/csharp/rule.adoc
  rules/S2198/resources.adoc
  rules/S2198/rspecator.adoc
  rules/S2198/rule.adoc
Labels: dotnet, layc

#2211 Modify rule S122: LaYC format
  rules/S122/abap/compliant.adoc
  rules/S122/abap/noncompliant.adoc
  rules/S122/abap/rule.adoc
  rules/S122/apex/compliant.adoc
  rules/S122/apex/noncompliant.adoc
  rules/S122/apex/rule.adoc
  rules/S122/cfamily/compliant.adoc
  rules/S122/cfamily/metadata.json
  rules/S122/cfamily/noncompliant.adoc
  rules/S122/cfamily/rule.adoc
  rules/S122/cobol/compliant.adoc
  rules/S122/cobol/noncompliant.adoc
  rules/S122/cobol/rule.adoc
  rules/S122/common/compliant.adoc
  rules/S122/common/noncompliant.adoc
  rules/S122/compliant.adoc
  rules/S122/csharp/compliant.adoc
  rules/S122/csharp/noncompliant.adoc
  rules/S122/csharp/rule.adoc
  rules/S122/description.adoc
  rules/S122/go/compliant.adoc
  rules/S122/go/noncompliant.adoc
  rules/S122/go/rule.adoc
  rules/S122/javascript/compliant.adoc
  rules/S122/javascript/noncompliant.adoc
  rules/S122/javascript/rule.adoc
  rules/S122/kotlin/compliant.adoc
  rules/S122/kotlin/noncompliant.adoc
  rules/S122/kotlin/rule.adoc
  rules/S122/noncompliant.adoc
  rules/S122/php/rule.adoc
  rules/S122/pli/compliant.adoc
  rules/S122/pli/noncompliant.adoc
  rules/S122/pli/rule.adoc
  rules/S122/plsql/compliant.adoc
  rules/S122/plsql/noncompliant.adoc
  rules/S122/plsql/rule.adoc
  rules/S122/python/compliant.adoc
  rules/S122/python/noncompliant.adoc
  rules/S122/python/rule.adoc
  rules/S122/ruby/compliant.adoc
  rules/S122/ruby/noncompliant.adoc
  rules/S122/ruby/rule.adoc
  rules/S122/rule.adoc
  rules/S122/scala/compliant.adoc
  rules/S122/scala/noncompliant.adoc
  rules/S122/scala/rule.adoc
  rules/S122/swift/compliant.adoc
  rules/S122/swift/noncompliant.adoc
  rules/S122/swift/rule.adoc
  rules/S122/tsql/compliant.adoc
  rules/S122/tsql/noncompliant.adoc
  rules/S122/tsql/rule.adoc
  rules/S122/vb6/compliant.adoc
  rules/S122/vb6/noncompliant.adoc
  rules/S122/vb6/rule.adoc
  rules/S122/vbnet/compliant.adoc
  rules/S122/vbnet/noncompliant.adoc
  rules/S122/vbnet/rule.adoc
Labels: common, layc

#2224 Modify rule S4487: fix missing space in code example
  rules/S4487/csharp/rule.adoc
Labels: dotnet, layc

#2174 Modify rule S6509: Adapt to LaYC
  rules/S6509/javascript/rule.adoc
Labels: jsts, layc

#2225 Modify rule S3451: fix wrong link
  rules/S3451/csharp/rule.adoc
Labels: dotnet, layc

#2202 Modify Rule S2681: LaYC comment blocks
  rules/S2681/cfamily/rule.adoc
  rules/S2681/common/example.adoc
  rules/S2681/compliant.adoc
  rules/S2681/csharp/example.adoc
  rules/S2681/csharp/rule.adoc
  rules/S2681/description.adoc
  rules/S2681/java/rule.adoc
  rules/S2681/javascript/example.adoc
  rules/S2681/javascript/rule.adoc
  rules/S2681/noncompliant.adoc
  rules/S2681/php/example.adoc
  rules/S2681/php/rule.adoc
  rules/S2681/rule.adoc
  rules/S2681/tsql/rule.adoc
Labels: common, layc

#2197 Modify rule S4635: Update title
  rules/S4635/csharp/metadata.json
  rules/S4635/csharp/rule.adoc
  rules/S4635/rspecator-dotnet.adoc
Labels: dotnet

#2230 Modify rule S4487: fix code example
  rules/S4487/csharp/rule.adoc
Labels: dotnet, layc

#2231 Modify rule S122: Add resources section
  rules/S122/csharp/rule.adoc
Labels: dotnet, layc

#2163 Deprecate rule S2165
  rules/S2165/java/metadata.json
Labels: java

#2235 Remove CFamily rules that are irrelevant
  rules/S1166/cfamily/metadata.json
  rules/S1166/cfamily/rule.adoc
  rules/S1168/cfamily/metadata.json
  rules/S1168/cfamily/rule.adoc
  rules/S140/cfamily/metadata.json
  rules/S140/cfamily/rule.adoc
  rules/S1444/cfamily/metadata.json
  rules/S1444/cfamily/rule.adoc
  rules/S1698/cfamily/metadata.json
  rules/S1698/cfamily/rule.adoc
  rules/S1944/cfamily/metadata.json
  rules/S1944/cfamily/rule.adoc
  rules/S1944/message.adoc
  rules/S2189/cfamily/metadata.json
  rules/S2189/cfamily/rule.adoc
  rules/S2201/cfamily/metadata.json
  rules/S2201/cfamily/rule.adoc
  rules/S2251/cfamily/metadata.json
  rules/S2251/cfamily/rule.adoc
  rules/S2384/cfamily/metadata.json
  rules/S2384/cfamily/rule.adoc
  rules/S3366/cfamily/metadata.json
  rules/S3366/cfamily/rule.adoc
  rules/S3931/cfamily/metadata.json
  rules/S3931/cfamily/rule.adoc
Labels: cfamily

#2011 Modify S5542: Learn-As-You-Code migration
  docs/header_names/allowed_framework_names.adoc
  rules/S5542/cfamily/how-to-fix-it/botan.adoc
  rules/S5542/cfamily/how-to-fix-it/cryptopp.adoc
  rules/S5542/cfamily/how-to-fix-it/openssl.adoc
  rules/S5542/cfamily/rule.adoc
  rules/S5542/common/fix/aes-compliant-example.adoc
  rules/S5542/common/fix/aes-noncompliant-example.adoc
  rules/S5542/common/fix/fix.adoc
  rules/S5542/common/fix/rsa-compliant-example.adoc
  rules/S5542/common/fix/rsa-noncompliant-example.adoc
  rules/S5542/common/resources/articles.adoc
  rules/S5542/common/resources/docs.adoc
  rules/S5542/common/resources/presentations.adoc
  rules/S5542/common/resources/standards.adoc
  rules/S5542/csharp/how-to-fix-it/dotnet.adoc
  rules/S5542/csharp/rule.adoc
  rules/S5542/description.adoc
  rules/S5542/impact.adoc
  rules/S5542/java/how-to-fix-it/java-cryptographic-extension.adoc
  rules/S5542/java/rule.adoc
  rules/S5542/javascript/how-to-fix-it/node-js.adoc
  rules/S5542/javascript/rule.adoc
  rules/S5542/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
  rules/S5542/kotlin/rule.adoc
  rules/S5542/php/how-to-fix-it/mcrypt.adoc
  rules/S5542/php/how-to-fix-it/openssl.adoc
  rules/S5542/php/rule.adoc
  rules/S5542/python/how-to-fix-it/pyca.adoc
  rules/S5542/python/how-to-fix-it/pycrypto.adoc
  rules/S5542/python/how-to-fix-it/pycryptodome.adoc
  rules/S5542/python/how-to-fix-it/pydes.adoc
  rules/S5542/python/rule.adoc
  rules/S5542/rationale.adoc
  rules/S5542/rule.adoc
  rules/S5542/summary.adoc
  rules/S5542/vbnet/how-to-fix-it/dotnet.adoc
  rules/S5542/vbnet/rule.adoc
Labels: cfamily, java, python, dotnet, php, jsts, kotlin, vb6, layc

#2241 layc-s6325-js
  rules/S6325/javascript/rule.adoc
Labels: jsts, layc

#2240 layc-s3735-js
  rules/S3735/javascript/rule.adoc
Labels: jsts, layc

#2166 Modify S4426: Learn-As-You-Code Migration
  rules/S4426/cfamily/how-to-fix-it/botan.adoc
  rules/S4426/cfamily/how-to-fix-it/cryptopp.adoc
  rules/S4426/cfamily/how-to-fix-it/openssl.adoc
  rules/S4426/cfamily/rule.adoc
  rules/S4426/common/extra-mile/pre-quantum.adoc
  rules/S4426/common/fix/aes.adoc
  rules/S4426/common/fix/code-rationale.adoc
  rules/S4426/common/fix/dh.adoc
  rules/S4426/common/fix/dl-group.adoc
  rules/S4426/common/fix/dsa.adoc
  rules/S4426/common/fix/ec.adoc
  rules/S4426/common/fix/fix.adoc
  rules/S4426/common/fix/rsa.adoc
  rules/S4426/common/resources/articles.adoc
  rules/S4426/common/resources/docs.adoc
  rules/S4426/common/resources/presentations.adoc
  rules/S4426/common/resources/standards.adoc
  rules/S4426/csharp/how-to-fix-it/dotnet.adoc
  rules/S4426/csharp/rule.adoc
  rules/S4426/description.adoc
  rules/S4426/impact.adoc
  rules/S4426/java/how-to-fix-it/java-cryptographic-extension.adoc
  rules/S4426/java/rule.adoc
  rules/S4426/javascript/how-to-fix-it/node-js.adoc
  rules/S4426/javascript/rule.adoc
  rules/S4426/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
  rules/S4426/kotlin/rule.adoc
  rules/S4426/php/how-to-fix-it/core.adoc
  rules/S4426/php/rule.adoc
  rules/S4426/python/how-to-fix-it/pyca.adoc
  rules/S4426/python/rule.adoc
  rules/S4426/rationale.adoc
  rules/S4426/summary.adoc
Labels: cfamily, java, python, dotnet, php, kotlin, javascript

#2251 S2925: Fix typos
  rules/S2925/csharp/rule.adoc
  rules/S2925/vbnet/rule.adoc
Labels: dotnet

#2236 Modify rule S5860: Adapt to LaYC
  rules/S5860/javascript/rule.adoc
Labels: jsts, layc

#2097 Modify S4423: Learn-As-You-Code Migration
  docs/header_names/allowed_framework_names.adoc
  rules/S4423/apex/metadata.json
  rules/S4423/apex/rule.adoc
  rules/S4423/azureresourcemanager/how-to-fix-it/azure-mysql.adoc
  rules/S4423/azureresourcemanager/how-to-fix-it/azure-storage-account.adoc
  rules/S4423/azureresourcemanager/rule.adoc
  rules/S4423/cfamily/how-to-fix-it/botan.adoc
  rules/S4423/cfamily/how-to-fix-it/curl.adoc
  rules/S4423/cfamily/how-to-fix-it/openssl.adoc
  rules/S4423/cfamily/rule.adoc
  rules/S4423/cloudformation/how-to-fix-it/api-gateway.adoc
  rules/S4423/cloudformation/how-to-fix-it/opensearch.adoc
  rules/S4423/cloudformation/rule.adoc
  rules/S4423/common/fix/fix.adoc
  rules/S4423/common/resources/articles.adoc
  rules/S4423/common/resources/docs.adoc
  rules/S4423/common/resources/presentations.adoc
  rules/S4423/common/resources/standards.adoc
  rules/S4423/csharp/how-to-fix-it/dotnet.adoc
  rules/S4423/csharp/rule.adoc
  rules/S4423/docker/how-to-fix-it/curl.adoc
  rules/S4423/docker/how-to-fix-it/wget.adoc
  rules/S4423/docker/rule.adoc
  rules/S4423/go/metadata.json
  rules/S4423/go/rule.adoc
  rules/S4423/highlighting.adoc
  rules/S4423/impact.adoc
  rules/S4423/java/how-to-fix-it/java-cryptographic-extension.adoc
  rules/S4423/java/how-to-fix-it/okhttp.adoc
  rules/S4423/java/rule.adoc
  rules/S4423/javascript/how-to-fix-it/aws-cdk.adoc
  rules/S4423/javascript/how-to-fix-it/node-js.adoc
  rules/S4423/javascript/rule.adoc
  rules/S4423/kotlin/how-to-fix-it/java-cryptographic-extension.adoc
  rules/S4423/kotlin/how-to-fix-it/okhttp.adoc
  rules/S4423/kotlin/rule.adoc
  rules/S4423/php/how-to-fix-it/core.adoc
  rules/S4423/php/rule.adoc
  rules/S4423/python/how-to-fix-it/aws-cdk.adoc
  rules/S4423/python/how-to-fix-it/openssl.adoc
  rules/S4423/python/how-to-fix-it/ssl.adoc
  rules/S4423/python/rule.adoc
  rules/S4423/rationale.adoc
  rules/S4423/ruby/metadata.json
  rules/S4423/ruby/rule.adoc
  rules/S4423/rust/metadata.json
  rules/S4423/rust/rule.adoc
  rules/S4423/scala/metadata.json
  rules/S4423/scala/rule.adoc
  rules/S4423/solidity/metadata.json
  rules/S4423/solidity/rule.adoc
  rules/S4423/summary.adoc
  rules/S4423/terraform/how-to-fix-it/aws-api-gateway.adoc
  rules/S4423/terraform/how-to-fix-it/aws-opensearch.adoc
  rules/S4423/terraform/how-to-fix-it/gcp-lb.adoc
  rules/S4423/terraform/rule.adoc
  rules/S4423/vbnet/how-to-fix-it/dotnet.adoc
  rules/S4423/vbnet/rule.adoc
Labels: cfamily, java, python, dotnet, php, iac, kotlin, javascript

#2253 S6640 - Make code samples follow code conventions
  rules/S6640/csharp/rule.adoc
Labels: dotnet

#2261 S6640: Set quickfix to infeasible
  rules/S6640/csharp/metadata.json
Labels: dotnet

#2271 Remove CFamily rules that were never implemented
  rules/S1041/cfamily/metadata.json
  rules/S1041/cfamily/rule.adoc
  rules/S1987/cfamily/metadata.json
  rules/S1987/cfamily/rule.adoc
  rules/S2197/cfamily/metadata.json
  rules/S2197/cfamily/rule.adoc
  rules/S888/cfamily/metadata.json
  rules/S888/cfamily/rule.adoc
  rules/S899/cfamily/metadata.json
  rules/S899/cfamily/rule.adoc
  rules/S979/cfamily/metadata.json
  rules/S979/cfamily/rule.adoc
Labels: cfamily

#2245 Modify rule S2755: LaYC format
  docs/header_names/allowed_framework_names.adoc
  rules/S2755/cfamily/how-to-fix-it/libxml2.adoc
  rules/S2755/cfamily/how-to-fix-it/xerces.adoc
  rules/S2755/cfamily/rule.adoc
  rules/S2755/common/fix/code-rationale.adoc
  rules/S2755/common/fix/xxe.adoc
  rules/S2755/common/resources/standards.adoc
  rules/S2755/csharp/how-to-fix-it/dot-net.adoc
  rules/S2755/csharp/rule.adoc
  rules/S2755/description.adoc
  rules/S2755/highlighting.adoc
  rules/S2755/impact.adoc
  rules/S2755/java/how-to-fix-it/dom4j.adoc
  rules/S2755/java/how-to-fix-it/java-se.adoc
  rules/S2755/java/how-to-fix-it/jdom2.adoc
  rules/S2755/java/rule.adoc
  rules/S2755/javascript/how-to-fix-it/libxmljs.adoc
  rules/S2755/javascript/rule.adoc
  rules/S2755/php/how-to-fix-it/core.adoc
  rules/S2755/php/rule.adoc
  rules/S2755/python/how-to-fix-it/lxml.adoc
  rules/S2755/python/how-to-fix-it/std.adoc
  rules/S2755/python/rule.adoc
  rules/S2755/rationale.adoc
  rules/S2755/summary.adoc
Labels: common, layc

#2249 Modify rule S6477: Adapt to LaYC
  rules/S6477/javascript/metadata.json
  rules/S6477/javascript/rule.adoc
Labels: jsts, layc

#2259 Modify rule S6486: Adapt to LaYC
  rules/S6486/javascript/metadata.json
  rules/S6486/javascript/rule.adoc
Labels: jsts, layc

#2282 Modify S4830(php): Fix code sample
  rules/S4830/php/how-to-fix-it/curl.adoc
Labels: php

#2217 Modify rule S107: Add T-SQL examples
  rules/S107/tsql/rule.adoc
Labels: dotnet

#2260 Modify rule S6479: Adapt to LaYC
  rules/S6479/javascript/metadata.json
  rules/S6479/javascript/rule.adoc
Labels: jsts, layc

#2290 Modify rule S1206: LaYC format
  rules/S1206/compliant.adoc
  rules/S1206/csharp/metadata.json
  rules/S1206/csharp/rule.adoc
  rules/S1206/description.adoc
  rules/S1206/java/rule.adoc
  rules/S1206/noncompliant.adoc
  rules/S1206/rule.adoc
  rules/S1206/see.adoc
Labels: java, dotnet, kotlin, layc

#2302 Modify rule S1527: Adapt to LaYC
  rules/S1527/javascript/rule.adoc
  rules/S1527/metadata.json
Labels: jsts, layc

#2301 Modify rule S2201: LaYC format
  rules/S2201/csharp/metadata.json
  rules/S2201/csharp/rule.adoc
Labels: dotnet

#2310 Modify rule S1764: LaYC format
  rules/S1764/csharp/metadata.json
  rules/S1764/csharp/rule.adoc
  rules/S1764/description.adoc
Labels: dotnet

#2311 Modify S1862: LaYC format
  rules/S1862/csharp/metadata.json
  rules/S1862/csharp/rule.adoc
  rules/S1862/description.adoc
  rules/S1862/vbnet/metadata.json
  rules/S1862/vbnet/rule.adoc
Labels: dotnet, layc

#2299 Modify rule S2688: LaYC format
  rules/S2688/comments-and-links.adoc
  rules/S2688/csharp/metadata.json
  rules/S2688/csharp/rule.adoc
  rules/S2688/description.adoc
  rules/S2688/java/metadata.json
  rules/S2688/java/rule.adoc
  rules/S2688/javascript/rule.adoc
Labels: java, dotnet, javascript, layc

#2254 Modify rule S6481: Adapt to LaYC
  rules/S6481/javascript/metadata.json
  rules/S6481/javascript/rule.adoc
Labels: jsts, layc

#2291 Modify rule S3456: LaYC format
  rules/S3456/csharp/rspecator.adoc
  rules/S3456/csharp/rule.adoc
Labels: dotnet

#2269 Modify S5527: Learn-As-You-Code migration
  docs/header_names/allowed_framework_names.adoc
  rules/S5527/cfamily/how-to-fix-it/botan.adoc
  rules/S5527/cfamily/how-to-fix-it/curl.adoc
  rules/S5527/cfamily/how-to-fix-it/openssl.adoc
  rules/S5527/cfamily/resources/docs.adoc
  rules/S5527/cfamily/rule.adoc
  rules/S5527/common/fix/code-rationale-explicit.adoc
  rules/S5527/common/fix/code-rationale-override.adoc
  rules/S5527/common/fix/code-rationale-setting.adoc
  rules/S5527/common/fix/code-rationale.adoc
  rules/S5527/common/fix/keytool.adoc
  rules/S5527/common/fix/validation.adoc
  rules/S5527/common/resources/standards.adoc
  rules/S5527/description.adoc
  rules/S5527/impact.adoc
  rules/S5527/java/how-to-fix-it/apache-commons-email.adoc
  rules/S5527/java/how-to-fix-it/java-ee.adoc
  rules/S5527/java/how-to-fix-it/java-se.adoc
  rules/S5527/java/metadata.json
  rules/S5527/java/rule.adoc
  rules/S5527/javascript/how-to-fix-it/node-js.adoc
  rules/S5527/javascript/rule.adoc
  rules/S5527/kotlin/how-to-fix-it/ok-http.adoc
  rules/S5527/kotlin/rule.adoc
  rules/S5527/php/how-to-fix-it/curl.adoc
  rules/S5527/php/rule.adoc
  rules/S5527/python/how-to-fix-it/std.adoc
  rules/S5527/python/rule.adoc
  rules/S5527/rationale.adoc
  rules/S5527/rule.adoc
  rules/S5527/summary.adoc
Labels: cfamily, java, python, php, kotlin, javascript

#2305 Modify rule S1716: LaYC format
  rules/S1716/python/rule.adoc
Labels: python, layc

#2304 Modify rule S3862: LaYC format
  rules/S3862/python/rule.adoc
Labels: python, layc

#2318 Modify rule S2345: LaYC format
  rules/S2345/csharp/rule.adoc
  rules/S2345/description.adoc
  rules/S2345/exceptions.adoc
  rules/S2345/metadata.json
  rules/S2345/resources.adoc
  rules/S2345/vbnet/rule.adoc
Labels: dotnet

#2303 Modify rule S1656: LaYC format
  rules/S1656/csharp/metadata.json
  rules/S1656/csharp/rule.adoc
Labels: dotnet

#2316 Modify rule S2114: LaYC format
  rules/S2114/csharp/rule.adoc
  rules/S2114/description.adoc
  rules/S2114/java/rule.adoc
  rules/S2114/kotlin/rule.adoc
  rules/S2114/message.adoc
  rules/S2114/rule.adoc
Labels: dotnet, layc

#2239 Modify rule S5146: Fix invalid Python sample
  rules/S5146/python/how-to-fix-it/flask.adoc
Labels: python

#2313 Modify rule S5549: LaYC format
  rules/S5549/python/rule.adoc
Labels: python, layc

#2246 Modify rule S6468: LaYC format
  rules/S6468/python/metadata.json
  rules/S6468/python/rule.adoc
Labels: python, layc

#2286 Modify rule S5707: LaYC format
  rules/S5707/python/rule.adoc
Labels: python, layc

#2289 Modify rule S5828: LaYC format
  rules/S5828/python/rule.adoc
Labels: python, layc

#2257 Modify Rule S5719: LaYC format
  rules/S5719/python/rule.adoc
Labels: python, layc

#2264 Modify rule S5724: LaYC format
  rules/S5724/python/rule.adoc
Labels: python, layc

#2263 Modify rule S5722: LaYC format
  rules/S5722/python/rule.adoc
Labels: python, layc

#2331 Modify rule S6442: Adapt to LaYC
  rules/S6442/javascript/rule.adoc
Labels: jsts, layc

#2332 Modify rule S4125: Adapt to LaYC
  rules/S4125/javascript/rule.adoc
Labels: jsts, layc

#2339 SONARIAC-915 Fix formatting and fields names
  rules/S6388/azureresourcemanager/rule.adoc
Labels: iac

#2319 Modify rule S3598: LayC format
  rules/S3598/csharp/rule.adoc
  rules/S3598/description.adoc
  rules/S3598/exceptions.adoc
  rules/S3598/metadata.json
  rules/S3598/resources.adoc
  rules/S3598/vbnet/rule.adoc
Labels: dotnet

#2334 Modify rule S3453: LaYC format
  rules/S3453/comments-and-links.adoc
  rules/S3453/csharp/compliant-code.adoc
  rules/S3453/csharp/noncompliant-code.adoc
  rules/S3453/csharp/rule.adoc
  rules/S3453/description.adoc
  rules/S3453/exceptions.adoc
  rules/S3453/highlighting.adoc
  rules/S3453/how-dotnet.adoc
  rules/S3453/message.adoc
  rules/S3453/metadata.json
  rules/S3453/resources-dotnet.adoc
  rules/S3453/rspecator.adoc
  rules/S3453/vbnet/compliant-code.adoc
  rules/S3453/vbnet/noncompliant-code.adoc
  rules/S3453/vbnet/rule.adoc
  rules/S3453/why-dotnet.adoc
Labels: dotnet, layc

#2330 Modify rule S3005: LaYC format
  rules/S3005/csharp/rule.adoc
Labels: dotnet
