Repository SonarSource/rspec, pull requests merged in 2023-04, with the labels that each got.

#1674 Modify rule S5950: Fix typos + rewording (CPP-4142)
  rules/S5950/cfamily/metadata.json
  rules/S5950/cfamily/rule.adoc
Labels: cfamily

#1721 Add diff view properties to new rule templates
  rspec-tools/rspec_template/multi_language/language_specific/rule.adoc
  rspec-tools/rspec_template/single_language/language_specific/rule.adoc
Labels: rspec system

#1725 Modify rule S6545: fix incorrect examples in the "How to fix it" section
  rules/S6545/python/rule.adoc
Labels: python

#349 Create rule S2175[kotlin]: Inappropriate collection calls should not be made
  rules/S2175/java/metadata.json
  rules/S2175/kotlin/metadata.json
  rules/S2175/kotlin/rule.adoc
  rules/S2175/metadata.json
Labels: kotlin

#340 Create rule S1206[kotlin]: "equals(Any?)" and "hashCode()" should be overridden in pairs
  rules/S1206/kotlin/metadata.json
  rules/S1206/kotlin/rule.adoc
Labels: kotlin

#1597 S3900: Update rule description and message
  rules/S3900/csharp/highlighting.adoc
  rules/S3900/csharp/message.adoc
  rules/S3900/csharp/rule.adoc
Labels: dotnet

#1731 Rule S3900: Add VB.NET
  rules/S3900/csharp/metadata.json
  rules/S3900/csharp/rule.adoc
  rules/S3900/highlighting.adoc
  rules/S3900/message.adoc
  rules/S3900/metadata.json
  rules/S3900/rspecator.adoc
  rules/S3900/vbnet/metadata.json
  rules/S3900/vbnet/rule.adoc
Labels: dotnet

#1742 Modify rule S6500: Adjust title and wording
  rules/S6500/description.adoc
  rules/S6500/implementation.adoc
  rules/S6500/metadata.json
Labels: iac

#1759 Modify rule S3655: Streamlining for C# and VB
  rules/S3655/description.adoc
  rules/S3655/vbnet/rule.adoc
Labels: dotnet

#1761 Modify rule S3900: Add method invocation to code sample
  rules/S3900/csharp/rule.adoc
Labels: dotnet

#1762 Modify rule S6570: Change description to avoid duplication
  rules/S6570/docker/rule.adoc
Labels: iac

#1775 Modify rule S2492: Fix the noncompliant example (PLSQL-S2492)
  rules/S2492/plsql/rule.adoc
Labels: plsql

#1793 Modify rule S5693: Add syntax highlighting and remove Java specific tags
  rules/S5693/java/metadata.json
  rules/S5693/java/rule.adoc
Labels: java

#1795 Modify rule S5506: Fix typo in issue message
  rules/S5506/cfamily/message.adoc
Labels: cfamily

#1788 Modify rule S923: Add link to CERT
  rules/S923/java/rule.adoc
Labels: java

#1797 Modify rule S986: CPP-4211 Align the RSPEC title with the implementation
  rules/S986/cfamily/metadata.json
Labels: cfamily

#1792 Modify rule S5659: Remove CERT tag
  rules/S5659/java/metadata.json
Labels: java

#1809 Modify rule S6598: Add missing sections
  rules/S6598/javascript/rule.adoc
Labels: jsts

#1810 Revert "Create rule S6601: Boolean expressions should be safe (#1779)"
  rules/S6601/javascript/metadata.json
  rules/S6601/javascript/rule.adoc
  rules/S6601/metadata.json
Labels: jsts

#1811 Modify rule S2094: improve JS rule definition
  rules/S2094/javascript/rule.adoc
Labels: jsts

#1813 Modify rule S6572: Add documentation link and minor fix
  rules/S6572/javascript/rule.adoc
Labels: jsts

#1816 Modify rule S6583: Add documentation header
  rules/S6583/javascript/rule.adoc
Labels: jsts

#1817 Modify rule S6594: Add documentation header
  rules/S6594/javascript/rule.adoc
Labels: jsts

#1815 Modify rule S6590: Add code example and documentation header
  rules/S6590/javascript/rule.adoc
Labels: jsts

#1814 Modify rule S6578: Add resources link to enums
  rules/S6578/javascript/rule.adoc
Labels: jsts

#1818 Modify rule S6544: Add column in front of pseudo title and add newline to fix list
  rules/S6544/javascript/metadata.json
  rules/S6544/javascript/rule.adoc
Labels: jsts

#1806 Deprecate rule S2041
  rules/S2041/php/metadata.json
Labels: php

#1824 Modify rule S6544: Fix code example
  rules/S6544/javascript/rule.adoc
Labels: jsts
