Repository SonarSource/rspec, pull requests merged in 2023-07, with the labels that each got.

#2327 Modify rule S5713: LaYC format
  rules/S5713/python/rule.adoc
Labels: python, layc

#2287 Modify rule S5708: LaYC format
  rules/S5708/python/rule.adoc
Labels: python, layc

#2355 Modify rule S6080: Adapt to LaYC
  rules/S6080/javascript/metadata.json
  rules/S6080/javascript/rule.adoc
Labels: jsts, layc

#2352 Modify rule S6079: Adapt to LaYC
  rules/S6079/javascript/rule.adoc
Labels: jsts, layc

#2343 Modify rule S3466: LayC format
  rules/S3466/csharp/rule.adoc
  rules/S3466/description.adoc
  rules/S3466/highlighting.adoc
  rules/S3466/metadata.json
  rules/S3466/rspecator.adoc
  rules/S3466/rule.adoc
  rules/S3466/vbnet/rule.adoc
Labels: dotnet

#2340 Modify rule S2252: LaYC format
  rules/S2252/csharp/compliant-code.adoc
  rules/S2252/csharp/metadata.json
  rules/S2252/csharp/noncompliant-code.adoc
  rules/S2252/csharp/rule.adoc
  rules/S2252/description.adoc
  rules/S2252/java/compliant-code.adoc
  rules/S2252/java/noncompliant-code.adoc
  rules/S2252/java/rule.adoc
  rules/S2252/message.adoc
  rules/S2252/rspecator.adoc
  rules/S2252/rule.adoc
  rules/S2252/vbnet/compliant-code.adoc
  rules/S2252/vbnet/metadata.json
  rules/S2252/vbnet/noncompliant-code.adoc
  rules/S2252/vbnet/rule.adoc
  rules/S2252/why.adoc
Labels: java, dotnet, layc

#2361 Modify rule S3925: LaYC format
  rules/S3925/comments-and-links.adoc
  rules/S3925/csharp/rule.adoc
  rules/S3925/highlighting.adoc
  rules/S3925/message.adoc
  rules/S3925/rule.adoc
Labels: dotnet, layc

#2347 Modify rule S2995: LaYC format
  rules/S2995/csharp/metadata.json
  rules/S2995/csharp/rule.adoc
Labels: dotnet, layc

#2353 Modify rule S2997: LaYC format
  rules/S2997/metadata.json
  rules/S2997/rule.adoc
Labels: dotnet

#2344 Modify rule S3244: LaYC format
  rules/S3244/csharp/rule.adoc
  rules/S3244/message.adoc
  rules/S3244/metadata.json
  rules/S3244/rspecator.adoc
  rules/S3244/rule.adoc
Labels: dotnet, layc

#2354 Modify rule S3603: LaYC format
  rules/S3603/csharp/rule.adoc
  rules/S3603/description.adoc
  rules/S3603/metadata.json
  rules/S3603/resources.adoc
  rules/S3603/vbnet/rule.adoc
Labels: dotnet

#2273 Modify rule S5607: LaYC format
  rules/S5607/python/rule.adoc
Labels: python, layc

#2321 Modify rule S2711: LaYC format
  rules/S2711/python/rule.adoc
Labels: python, layc

#2364 Modify rule S3887: LaYC format
  rules/S3887/rule.adoc
Labels: dotnet

#2294 Modify rule S2259: LaYC format
  rules/S2259/csharp/compliant-code.adoc
  rules/S2259/csharp/exception-code-analysis-attr.adoc
  rules/S2259/csharp/exception-code-debug-assert.adoc
  rules/S2259/csharp/exception-code-extension-method.adoc
  rules/S2259/csharp/exception-code-rider-attr.adoc
  rules/S2259/csharp/exception-code-unreachable.adoc
  rules/S2259/csharp/metadata.json
  rules/S2259/csharp/noncompliant-code.adoc
  rules/S2259/csharp/rule.adoc
  rules/S2259/how-dotnet.adoc
  rules/S2259/resources-dotnet.adoc
  rules/S2259/rspecator-dotnet.adoc
  rules/S2259/rule.adoc
  rules/S2259/see.adoc
  rules/S2259/vbnet/compliant-code.adoc
  rules/S2259/vbnet/exception-code-analysis-attr.adoc
  rules/S2259/vbnet/exception-code-debug-assert.adoc
  rules/S2259/vbnet/exception-code-extension-method.adoc
  rules/S2259/vbnet/exception-code-rider-attr.adoc
  rules/S2259/vbnet/exception-code-unreachable.adoc
  rules/S2259/vbnet/metadata.json
  rules/S2259/vbnet/noncompliant-code.adoc
  rules/S2259/vbnet/rule.adoc
  rules/S2259/why-dotnet.adoc
Labels: dotnet, layc

#2365 Modify rule S2934: LaYC format
  rules/S2934/csharp/rule.adoc
Labels: dotnet, layc

#2317 Modify rule S2319: LaYC format
  rules/S2319/python/rule.adoc
Labels: python, layc

#2262 Modify rule S5714: LaYC format
  rules/S5714/python/rule.adoc
Labels: python, layc

#2374 Modify rule S2695: Update rule according to the LayC
  rules/S2695/description.adoc
  rules/S2695/java/rule.adoc
  rules/S2695/kotlin/rule.adoc
  rules/S2695/metadata.json
Labels: java, layc

#2368 Modify rule S6439: Adapt to LaYC
  rules/S6439/javascript/rule.adoc
Labels: jsts, layc

#2376 Modify rule S2718: Update rule according to the LayC
  rules/S2718/java/metadata.json
  rules/S2718/java/rule.adoc
Labels: java, layc

#2369 Modify rule S6438: Adapt to LaYC
  rules/S6438/javascript/rule.adoc
Labels: jsts, layc

#2371 Modify rule S3610: LaYC format
  rules/S3610/csharp/metadata.json
  rules/S3610/csharp/rule.adoc
Labels: dotnet, layc

#2377 Modify rule S3453: Update rule link format
  rules/S3453/resources-dotnet.adoc
Labels: dotnet, layc

#2375 Modify rule S1656: Update VB.NET code examples
  rules/S1656/csharp/rule.adoc
  rules/S1656/vbnet/rule.adoc
Labels: dotnet

#2346 Modify rule S4428: LaYC format
  rules/S4428/csharp/rule.adoc
  rules/S4428/description.adoc
  rules/S4428/metadata.json
  rules/S4428/resources.adoc
  rules/S4428/vbnet/rule.adoc
Labels: dotnet

#2325 Modify rule S5712: LaYC format
  rules/S5712/python/rule.adoc
Labels: python, layc

#2380 S3610: Set quickfix field to targeted
  rules/S3610/csharp/metadata.json
Labels: dotnet, layc

#2372 Modify rule S2183: LaYC format
  rules/S2183/csharp/metadata.json
  rules/S2183/csharp/rule.adoc
  rules/S2183/java/rule.adoc
  rules/S2183/message.adoc
  rules/S2183/rspecator.adoc
Labels: java, layc

#2382 Modify rule S3168: LaYC format
  rules/S3168/csharp/metadata.json
  rules/S3168/csharp/rule.adoc
Labels: dotnet, layc

#2384 Modify rule S4260: LaYC format
  rules/S4260/csharp/rule.adoc
  rules/S4260/description.adoc
  rules/S4260/resources.adoc
  rules/S4260/vbnet/rule.adoc
  rules/S4260/why.adoc
Labels: dotnet

#2391 Modify rule S3984: LaYC format
  rules/S3984/csharp/metadata.json
  rules/S3984/csharp/rule.adoc
Labels: dotnet, layc

#2378 Modify rule S6435: Adapt to LaYC
  rules/S6435/javascript/metadata.json
  rules/S6435/javascript/rule.adoc
Labels: jsts, layc

#2393 Modify rule S6092: Adapt to LaYC
  rules/S6092/javascript/rule.adoc
Labels: jsts, layc

#2397 Modify rule S2864: Update rule according to the LayC
  rules/S2864/java/metadata.json
  rules/S2864/java/rule.adoc
Labels: java, layc

#2394 Modify rule S3616: Adapt to LaYC
  rules/S3616/javascript/rule.adoc
Labels: jsts, layc

#2392 Modify rule S1848: LaYC format
  rules/S1848/csharp/metadata.json
  rules/S1848/csharp/rule.adoc
  rules/S1848/description.adoc
Labels: dotnet, layc

#2396 Modify rule S1048: LaYC format
  rules/S1048/csharp/compliant-code.adoc
  rules/S1048/csharp/metadata.json
  rules/S1048/csharp/noncompliant-code.adoc
  rules/S1048/csharp/rule.adoc
  rules/S1048/how-dotnet.adoc
  rules/S1048/resources-dotnet.adoc
  rules/S1048/rspecator-dotnet.adoc
  rules/S1048/vbnet/compliant-code.adoc
  rules/S1048/vbnet/metadata.json
  rules/S1048/vbnet/noncompliant-code.adoc
  rules/S1048/vbnet/rule.adoc
  rules/S1048/why-dotnet.adoc
Labels: dotnet, layc

#2408 Fix the rule-id link format
  docs/link_formatting.adoc
Labels: rspec system

#2404 Modify rule S2123: LaYC format
  rules/S2123/csharp/metadata.json
  rules/S2123/csharp/rule.adoc
Labels: dotnet, layc

#2285 Modify Rule S3363: Add VB.NET description
  rules/S3363/csharp/rule.adoc
  rules/S3363/introduction-dotnet.adoc
  rules/S3363/vbnet/metadata.json
  rules/S3363/vbnet/rule.adoc
  rules/S3363/why-dotnet.adoc
Labels: dotnet

#2400 Modify rule S3696: Adapt to LaYC
  rules/S3696/javascript/rule.adoc
Labels: jsts, layc

#2402 Modify rule S3531: Adapt to LaYC
  rules/S3531/javascript/metadata.json
  rules/S3531/javascript/rule.adoc
Labels: jsts, layc

#2335 Modify rule S2053: LaYC format
  rules/S2053/comments-and-links.adoc
  rules/S2053/common/fix/auto-salt.adoc
  rules/S2053/common/fix/code-rationale.adoc
  rules/S2053/common/fix/salt.adoc
  rules/S2053/common/resources/standards.adoc
  rules/S2053/csharp/how-to-fix-it/dot-net.adoc
  rules/S2053/csharp/rule.adoc
  rules/S2053/description.adoc
  rules/S2053/impact.adoc
  rules/S2053/java/how-to-fix-it/java-se.adoc
  rules/S2053/java/rule.adoc
  rules/S2053/kotlin/how-to-fix-it/java-se.adoc
  rules/S2053/kotlin/rule.adoc
  rules/S2053/php/how-to-fix-it/core.adoc
  rules/S2053/php/rule.adoc
  rules/S2053/python/how-to-fix-it/std.adoc
  rules/S2053/python/rule.adoc
  rules/S2053/rationale.adoc
  rules/S2053/recommended.adoc
  rules/S2053/see.adoc
  rules/S2053/summary.adoc
  rules/S2053/vbnet/how-to-fix-it/dot-net.adoc
  rules/S2053/vbnet/rule.adoc
Labels: common, layc

#2414 Modify rule S3453: Remove link to S1118
  rules/S3453/resources-dotnet.adoc
Labels: dotnet, layc

#2416 Fix S3887+S3603+S3927 minor issues after validation
  rules/S3603/csharp/rule.adoc
  rules/S3603/vbnet/rule.adoc
  rules/S3887/rule.adoc
  rules/S3927/csharp/rule.adoc
  rules/S3927/description.adoc
  rules/S3927/vbnet/rule.adoc
Labels: dotnet, layc

#2415 Modify rule S2259: Remove anchor link
  rules/S2259/why-dotnet.adoc
Labels: dotnet, layc

#2417 Modify rule S2995: Remove S3898 link
  rules/S2995/csharp/rule.adoc
Labels: dotnet, layc

#2399 Modify rule S4624: Adapt to LaYC
  rules/S4624/javascript/rule.adoc
Labels: jsts, layc

#2405 Modify rule S1751: LaYC format
  rules/S1751/csharp/metadata.json
  rules/S1751/csharp/rule.adoc
  rules/S1751/rspecator-dotnet.adoc
  rules/S1751/vbnet/metadata.json
  rules/S1751/vbnet/rule.adoc
Labels: dotnet, layc

#2419 Modify rule S3785: Adapt to LaYC
  rules/S3785/javascript/rule.adoc
Labels: jsts, layc

#2418 Modify rule S6443: Adapt to LaYC
  rules/S6443/javascript/rule.adoc
Labels: jsts, layc

#2412 Modify rule S2924: Update rule according to the LayC
  rules/S2924/java/metadata.json
  rules/S2924/java/rule.adoc
Labels: java, layc

#2423 Modify rule S4275: Fix compliant tag
  rules/S4275/javascript/rule.adoc
Labels: jsts, layc

#2422 Modify rule S3834: add BigInt, rewrite the description
  rules/S3834/javascript/metadata.json
  rules/S3834/javascript/rule.adoc
Labels: jsts

#2421 Modify rule S3504: Adapt to LaYC
  rules/S3504/javascript/rule.adoc
Labels: jsts, layc

#2427 Modify rule S6440: Adapt to LaYC
  rules/S6440/javascript/rule.adoc
Labels: jsts, layc

#2426 Modify rule S6441: Adapt to LaYC
  rules/S6441/javascript/rule.adoc
Labels: jsts, layc

#2429 Modify rule S1536: Adapt to LaYC
  rules/S1536/javascript/rule.adoc
Labels: jsts, layc

#2431 Modify rule S4123: Adapt to LaYC
  rules/S4123/javascript/rule.adoc
Labels: jsts, layc

#2433 Modify rule S2870: Adapt to LaYC
  rules/S2870/javascript/rule.adoc
Labels: jsts, layc

#2428 Modify rule S1751: Fix diff typo
  rules/S1751/csharp/rule.adoc
Labels: dotnet, layc

#2432 Cross reference guides and cosmetics improvements
  docs/description.adoc
Labels: rspec system

#2434 Modify rule S4619: Adapt to LaYC
  rules/S4619/javascript/rule.adoc
Labels: jsts, layc

#2435 Modify rule S2392: Adapt to LaYC
  rules/S2392/javascript/rule.adoc
Labels: jsts, layc

#2439 Modify rule S935: LaYC format
  rules/S935/cfamily/rule.adoc
Labels: cfamily, layc

#2444 Modify rule S6487: LaYC format
  rules/S6487/cfamily/rule.adoc
Labels: cfamily, layc

#2443 Modify rule S961: LaYC format
  rules/S961/cfamily/rule.adoc
Labels: cfamily, layc

#2437 Modify rule S3834: Adapt to LaYC
  rules/S3834/javascript/rule.adoc
Labels: jsts, layc

#2446 Modify rule S4030: Adapt to LaYC
  rules/S4030/description.adoc
  rules/S4030/javascript/rule.adoc
Labels: jsts, layc

#2440 Modify rule S4140: Adapt to LaYC
  rules/S4140/javascript/metadata.json
  rules/S4140/javascript/rule.adoc
Labels: jsts, layc

#2451 Modify rule S3863: Adapt to LaYC
  rules/S3863/javascript/metadata.json
  rules/S3863/javascript/rule.adoc
Labels: jsts, layc

#2455 Modify rule S3799: Adapt to LaYC
  rules/S3799/javascript/rule.adoc
Labels: jsts, layc

#2452 Modify rule S4634: Adapt to LaYC
  rules/S4634/javascript/rule.adoc
Labels: jsts, layc

#2457 Modify rule S3782: Adapt to LaYC
  rules/S3782/javascript/rule.adoc
Labels: jsts, layc

#2463 Modify rule S3579: Adapt to LaYC
  rules/S3579/javascript/rule.adoc
Labels: jsts, layc

#2464 Modify rule S2432: Adapt to LaYC
  rules/S2432/javascript/rule.adoc
Labels: jsts, layc

#2461 Focus the search input on search-page load
  frontend/src/SearchPage.tsx
  frontend/src/__tests__/__snapshots__/SearchPage.test.tsx.snap
Labels: rspec system

#2472 Modify rule S6641: Add missing comma to code example
  rules/S6641/csharp/how-to-fix-it/dotnet-core.adoc
Labels: dotnet

#2479 Modify rule S3984: Adapt to LaYC
  rules/S3984/javascript/rule.adoc
Labels: jsts, layc

#2478 Modify rule S2310: Adapt to LaYC
  rules/S2310/javascript/rule.adoc
Labels: jsts, layc

#2475 Modify rule S2703: Adapt to LaYC
  rules/S2703/javascript/rule.adoc
Labels: jsts, layc

#2484 Modify rule S3800: Adapt to LaYC
  rules/S3800/javascript/rule.adoc
Labels: jsts, layc

#2486 Modify rule S3001: Adapt to LaYC
  rules/S3001/javascript/rule.adoc
Labels: jsts, layc

#2491 Modify rule S6351: Adapt to LaYC
  rules/S6351/javascript/rule.adoc
Labels: jsts, layc

#2492 Modify rule S1314: Adapt to LaYC
  rules/S1314/javascript/rule.adoc
Labels: jsts, layc

#2489 Modify rule S3500: Adapt to LaYC
  rules/S3500/javascript/metadata.json
  rules/S3500/javascript/rule.adoc
Labels: jsts, layc

#2493 Modify rule S5972: LaYC format
  rules/S5972/cfamily/rule.adoc
Labels: cfamily, layc

#2498 Modify rule S3686: Adapt to LaYC
  rules/S3686/javascript/metadata.json
  rules/S3686/javascript/rule.adoc
Labels: jsts, layc

#2499 Modify rule S4822: Adapt to LaYC
  rules/S4822/javascript/rule.adoc
Labels: jsts, layc

#2501 Modify rule S2814: Adapt to LaYC
  rules/S2814/rule.adoc
Labels: jsts, layc

#2449 Modify rule S6427: LaYC format
  rules/S6427/cfamily/rule.adoc
Labels: cfamily, layc

#2502 Modify rule S955: LaYC format
  rules/S955/cfamily/rule.adoc
Labels: cfamily, layc

#2510 Modify rule S1533: Adapt to LaYC
  rules/S1533/javascript/rule.adoc
Labels: jsts, layc

#2508 Modify rule S2685: Adapt to LaYC
  rules/S2685/javascript/rule.adoc
Labels: jsts, layc

#2517 Modify rule S1516: Adapt to LaYC
  rules/S1516/javascript/rule.adoc
Labels: jsts, layc

#2526 Modify rule S6401: Fix typo in code sample
  rules/S6401/terraform/rule.adoc
Labels: iac

#2519 Modify rule S1529: Adapt to LaYC
  rules/S1529/javascript/rule.adoc
Labels: jsts, layc

#2535 Modify rule S2999: Adapt to LaYC
  rules/S2999/javascript/rule.adoc
Labels: jsts, layc

#2540 Modify rule S1321: Adapt to LaYC
  rules/S1321/javascript/rule.adoc
Labels: jsts, layc

#2543 Modify rule S3699: Adapt to LaYC
  rules/S3699/compliant.adoc
  rules/S3699/javascript/metadata.json
  rules/S3699/javascript/rule.adoc
  rules/S3699/noncompliant.adoc
Labels: jsts, layc

#2531 Modify S6317: Compliant-ized the text
  rules/S6317/terraform/rule.adoc
Labels: iac

#2529 Modify S6329: Make GCP sample safer
  rules/S6329/terraform/rule.adoc
Labels: iac

#2536 Modify S6414: Fix Ask-yourself
  rules/S6414/terraform/rule.adoc
Labels: iac

#2550 Modify rule S1848: Adapt to LaYC
  rules/S1848/javascript/rule.adoc
Labels: jsts, layc

#2522 Modify S6333: Improve the general text
  rules/S6333/ask-yourself.adoc
  rules/S6333/description.adoc
  rules/S6333/metadata.json
  rules/S6333/recommended.adoc
  rules/S6333/see.adoc
Labels: iac

#2552 Modify rule S1788: Adapt to LaYC
  rules/S1788/javascript/rule.adoc
Labels: jsts, layc

#2542 Modify rule S2188: LayC review [SONARJAVA-4490]
  rules/S2188/java/rule.adoc
Labels: java, layc

#2511 Modify rule S2186: Review rule description [SONARJAVA-4490]
  rules/S2186/java/rule.adoc
Labels: java, layc

#2527 Modify rule S2204: reworked rule description for LayC format [SONARJAVA-4490]
  rules/S2204/java/rule.adoc
Labels: java, layc

#2544 Modify rule S2226: reworked rule description for LayC format [SONARJAVA-4490]
  rules/S2226/java/rule.adoc
Labels: java, layc

#2534 Modify rule S5267: LaYC format
  rules/S5267/cfamily/rule.adoc
Labels: cfamily, layc

#2453 Modify rule S6491: LaYC format
  rules/S6491/cfamily/rule.adoc
Labels: cfamily, layc

#2512 Modify rule S956: LaYC format
  rules/S956/cfamily/rule.adoc
Labels: cfamily, layc

#2562 Modify rule S2639: Adapt to LaYC
  rules/S2639/javascript/rule.adoc
Labels: jsts, layc

#2564 Modify rule S6325: Adapt to LaYC
  rules/S6325/javascript/rule.adoc
Labels: jsts, layc

#2558 Modify S6431(k8s): Improve sample
  rules/S6431/kubernetes/rule.adoc
Labels: iac

#2559 Modify S1135(k8s): Improve the code sample
  rules/S1135/kubernetes/rule.adoc
Labels: iac

#2560 Modify S6502: Improve description
  rules/S6502/docker/rule.adoc
Labels: iac

#2565 Modify rule S1439: Adapt to LaYC
  rules/S1439/javascript/rule.adoc
Labels: jsts, layc

#2567 Modify rule S6426: Adapt to LaYC
  rules/S6426/javascript/rule.adoc
Labels: jsts, layc

#2568 Modify rule S3735: Adapt to LaYC
  rules/S3735/javascript/rule.adoc
Labels: jsts, layc

#2555 Modify rule S1125: Adapt to LaYC
  rules/S1125/javascript/rule.adoc
Labels: jsts, layc

#2577 Modify rule S3626: Adapt to LaYC
  rules/S3626/javascript/rule.adoc
Labels: jsts, layc

#2578 Modify rule S1128: Adapt to LaYC
  rules/S1128/javascript/rule.adoc
Labels: jsts, layc

#2547 Modify rule S2230: LaYC review [SONARJAVA-4490]
  rules/S2230/java/rule.adoc
Labels: java, layc

#2569 Modify S6500(docker): Improve samples
  rules/S6500/docker/rule.adoc
Labels: iac

#2566 Modify S6505(docker): Improve samples
  rules/S6505/docker/rule.adoc
Labels: iac

#2556 Modify S6303: Add more risks
  rules/S6303/description.adoc
Labels: iac

#2532 Modify S4423(Azure): Add MSSQL sample
  docs/header_names/allowed_framework_names.adoc
  rules/S4423/terraform/how-to-fix-it/azure-mssql.adoc
  rules/S4423/terraform/rule.adoc
Labels: iac

#2571 Modify S6333(Cfn): Improve samples
  rules/S6333/cloudformation/rule.adoc
Labels: iac

#2585 Modify rule S6303: Fix invalid code samples
  rules/S6303/cloudformation/rule.adoc
  rules/S6303/terraform/rule.adoc
Labels: iac

#2581 Modify rule S2234: Adapt to LaYC
  rules/S2234/javascript/rule.adoc
Labels: jsts, layc

#2582 Modify rule S3403: Adapt to LaYC
  rules/S3403/javascript/rule.adoc
Labels: jsts, layc

#2570 Modify S6471(docker): Improve overall rule
  rules/S6471/docker/rule.adoc
Labels: iac

#2572 Modify S6329(Cfn): Improve samples
  rules/S6329/cloudformation/rule.adoc
Labels: iac

#2586 Modify S6302(Cfn): Improve samples
  rules/S6302/cloudformation/rule.adoc
Labels: iac

#2587 Modify S6294(Cfn): Improve samples
  rules/S6294/cloudformation/rule.adoc
Labels: iac

#2588 Modify S6321(Cfn): Improve samples
  rules/S6321/cloudformation/rule.adoc
Labels: iac

#2551 Modify S6413(tf): Add AWS Cloudwatch
  rules/S6413/terraform/rule.adoc
Labels: iac

#2505 Modify rule S6459: LaYC format
  rules/S6459/cfamily/rule.adoc
Labels: cfamily, layc

#2597 Modify rule S2990: Fix typo
  rules/S2990/javascript/rule.adoc
Labels: jsts

#2349 Modify rule S3400: CPP-3455 Delete this rule for CFamily
  rules/S3400/cfamily/metadata.json
Labels: cfamily

#2598 Modify rule S2154: reworked rule description for LayC format [SONARJAVA-4490]
  rules/S2154/java/rule.adoc
Labels: java, layc

#2592 Modify rule S2272: LaYC review [SONARJAVA-4490]
  rules/S2272/java/rule.adoc
Labels: java, layc

#2591 Modify ryle S2254: LaYC review [SONARJAVA-4490]
  rules/S2254/java/rule.adoc
Labels: java, layc

#2600 Modify S2078(java+common): Improved fix
  rules/S2078/common/fix/validation.adoc
  rules/S2078/java/how-to-fix-it/java-se.adoc
Labels: java

#2604 Modify rule S5863: Adapt to LaYC
  rules/S5863/javascript/rule.adoc
Labels: jsts, layc

#2606 Modify rule S2699: Adapt to LaYC
  rules/S2699/javascript/rule.adoc
Labels: jsts, layc

#2596 Modify rule S836: Adapt to LaYC
  rules/S836/cfamily/rule.adoc
Labels: cfamily, layc
