Repository SonarSource/rspec, pull requests merged in 2023-03, with the labels that each got.

#1571 Modify rule S4545: Add VB.NET specifics, Move C# specifics
  rules/S4545/csharp/rule.adoc
  rules/S4545/highlighting.adoc
  rules/S4545/message.adoc
  rules/S4545/rule.adoc
  rules/S4545/vbnet/rule.adoc
Labels: dotnet

#1570 Modify rule S2445: Add C# description and samples
  rules/S2445/csharp/highlighting.adoc
  rules/S2445/csharp/message.adoc
  rules/S2445/csharp/metadata.json
  rules/S2445/csharp/rule.adoc
  rules/S2445/java/highlighting.adoc
  rules/S2445/java/message.adoc
  rules/S2445/java/metadata.json
  rules/S2445/java/rule.adoc
  rules/S2445/metadata.json
  rules/S2445/rule-except-see.adoc
  rules/S2445/rule.adoc
  rules/S2445/see.adoc
Labels: dotnet

#1572 S3398: Add C# description
  rules/S3398/csharp/rule.adoc
Labels: dotnet

#1495 Modify rule S6470(Docker): Improve message
  rules/S6470/implementation.adoc
Labels: iac

#1590 Modify rule S1481: provide education description
  rules/S1481/javascript/rule.adoc
Labels: javascript

#1615 Modify rule S2137: Change text to include JavaScript standard builtins
  rules/S2137/javascript/rule.adoc
Labels: jsts

#1618 Modify rule S1534: Extend the scope to all kinds of class members
  rules/S1534/javascript/message.adoc
  rules/S1534/javascript/metadata.json
  rules/S1534/javascript/rule.adoc
Labels: jsts

#1632 Update create new rule template to education format
  rspec-tools/rspec_template/multi_language/language_specific/rule.adoc
  rspec-tools/rspec_template/single_language/language_specific/rule.adoc
Labels: rspec system

#1634 Modify rule S1862: Consider identical cases of switch statements
  rules/S1862/javascript/rule.adoc
Labels: jsts

#1651 Modify rule S3649: Fix typo in code samples
  rules/S3649/php/how-to-fix-it/core.adoc
Labels: php

#1642 description.adoc: add link to the Coding rule guidelines on SonarQube
  docs/description.adoc
Labels: rspec system

#1641 metadata.adoc: add link to the Coding rule guidelines on SonarQube
  docs/metadata.adoc
Labels: rspec system

#1528 S5856: Add C# and VB.NET
  rules/S5856/csharp/metadata.json
  rules/S5856/csharp/rule.adoc
  rules/S5856/java/rule.adoc
  rules/S5856/javascript/rule.adoc
  rules/S5856/kotlin/rule.adoc
  rules/S5856/message.adoc
  rules/S5856/php/rule.adoc
  rules/S5856/python/rule.adoc
  rules/S5856/rspecator.adoc
  rules/S5856/vbnet/metadata.json
  rules/S5856/vbnet/rule.adoc
Labels: dotnet

#1681 Modify rule S2222: Update description
  rules/S2222/csharp/description.adoc
  rules/S2222/csharp/rule.adoc
  rules/S2222/description-dotnet.adoc
  rules/S2222/vbnet/description.adoc
  rules/S2222/vbnet/rule.adoc
Labels: dotnet

#1683 Modify rule S4326: Add quickfix support
  rules/S4326/javascript/metadata.json
Labels: jsts

#1698 Modify rule S3402: Consider the addition assignment operator
  rules/S3402/javascript/rule.adoc
Labels: jsts

#1702 Modify rule S131: Ignore exhaustive switches on unions and enums
  rules/S131/javascript/metadata.json
  rules/S131/javascript/rule.adoc
Labels: jsts
