Repository SonarSource/rspec, pull requests merged in 2023-12, with the labels that each got.

#3486 Use newer sonar-scanner to get Java 17 required for Sonar analysis
  .cirrus.yml
Labels: rspec system

#3487 Modify rule S6839: Fix typos in Python code snippets in description
  rules/S6839/python/rule.adoc
Labels: python

#3489 Use NodeJS 16 to run Sonar analysis
  ci/Dockerfile
  ci/frontend-tests-dockerfile
Labels: rspec system

#3490 Modify rule S3518: Correct examples to be valid python code
  rules/S3518/python/rule.adoc
Labels: python

#3496 Modify rule S3630: Clarify in RSPEC what is expected from users before C++20 (CPP-4803)
  rules/S3630/cfamily/rule.adoc
Labels: cfamily

#3498 Deprecate rule S4792 (APPSEC-1407)
  rules/S4792/metadata.json
Labels: java, appsec, python, dotnet, php, vb6

#3504 Deprecate rule S5743 (APPSEC-1410)
  rules/S5743/javascript/metadata.json
  rules/S5743/metadata.json
Labels: appsec, jsts

#3507 Delete rule S5750 (APPSEC-1411)
  rules/S5750/javascript/metadata.json
  rules/S5750/metadata.json
Labels: appsec, jsts

#3495 Modify rule S1876: No more a hotspot, now a code smell (APPSEC-1400)
  rules/S1876/html/metadata.json
Labels: html

#3512 Modify rule S6864: Update text regarding namespaces
  rules/S6864/kubernetes/rule.adoc
Labels: iac

#3516 Modify Rule S6865: Add CWE 306
  rules/S6865/kubernetes/metadata.json
  rules/S6865/kubernetes/rule.adoc
Labels: appsec

#3519 Fix asciidoc w.r.t. C++
  rules/S1079/cfamily/rule.adoc
  rules/S1081/cfamily/how-to-fix-it/buffer-overflow.adoc
  rules/S1081/rationale.adoc
  rules/S2259/cfamily/rule.adoc
  rules/S3574/cfamily/rule.adoc
  rules/S5270/cfamily/rule.adoc
  rules/S5272/cfamily/rule.adoc
  rules/S5487/cfamily/rule.adoc
  rules/S5847/cfamily/rule.adoc
  rules/S6191/cfamily/rule.adoc
  rules/S6391/cfamily/rule.adoc
  rules/S6494/cfamily/rule.adoc
  rules/S6655/cfamily/rule.adoc
  rules/S874/cfamily/rule.adoc
  rules/S954/cfamily/rule.adoc
Labels: cfamily

#3518 Fix typo in S1125 description
  rules/S1125/apex/rule.adoc
  rules/S1125/csharp/rule.adoc
  rules/S1125/description.adoc
  rules/S1125/go/rule.adoc
  rules/S1125/how-to-fix-it.adoc
  rules/S1125/javascript/rule.adoc
  rules/S1125/kotlin/rule.adoc
  rules/S1125/php/rule.adoc
  rules/S1125/plsql/rule.adoc
  rules/S1125/rule.adoc
  rules/S1125/scala/rule.adoc
  rules/S1125/vb6/rule.adoc
  rules/S1125/vbnet/rule.adoc
Labels: common

#3525 RULEAPI-800 Detect usages of C++ instead of {cpp} in asciidoc
  rspec-tools/rspec_tools/validation/sanitize_asciidoc.py
  rspec-tools/tests/resources/asciidoc/valid.adoc
  rspec-tools/tests/resources/invalid-asciidoc/snapshots/unnamed_language.txt
  rspec-tools/tests/resources/invalid-asciidoc/unnamed_language.adoc
  rspec-tools/tests/validation/test_asciidoc_sanitization.py
  rules/S116/cfamily/rule.adoc
  rules/S1669/cfamily/rule.adoc
  rules/S3519/cfamily/rule.adoc
  rules/S4263/cfamily/rule.adoc
  rules/S5273/cfamily/rule.adoc
  rules/S5487/cfamily/rule.adoc
  rules/S6180/cfamily/rule.adoc
  rules/S6226/cfamily/rule.adoc
  rules/S6232/cfamily/rule.adoc
  rules/S995/cfamily/rule.adoc
Labels: rspec system, common
