Repository SonarSource/rspec, pull requests merged in 2024-02, with the labels that each got.

#3582 Modify rule S4123: remove hint about JSdoc and add it to exception
  rules/S4123/javascript/rule.adoc
Labels: jsts

#3599 Modify rule S927: Update rule description
  rules/S927/why-dotnet.adoc
Labels: dotnet

#3447 Modify rule S1242(cfamily):CPP-4790 Improve documentation with 'using'
  rules/S1242/cfamily/rule.adoc
Labels: cfamily

#3575 Modify rule S6661: clarify advantages of new syntax
  rules/S6661/javascript/rule.adoc
Labels: jsts

#3587 Modify rule S4323: Ignore nullable types
  rules/S4323/javascript/rule.adoc
Labels: jsts

#3629 APPSEC-1479: S6910 Adjustment to make RSPEC consistent with Sonar Text
  rules/S6910/secrets/rule.adoc
Labels: appsec

#3632 Modify rule: Update rule descriptions
  rules/S1110/description.adoc
  rules/S2551/vbnet/rule.adoc
  rules/S3449/vbnet/rule.adoc
  rules/S3603/description.adoc
Labels: dotnet

#3626 Modify rule S6582: Change severity to minor and improve description
  rules/S6582/javascript/metadata.json
  rules/S6582/javascript/rule.adoc
Labels: jsts

#3608 Modify rule S1186: Ignore noop-like functions, arrows, and constructors
  rules/S1186/javascript/rule.adoc
Labels: jsts

#3637 Modify rule S5131: Fix Spring example
  rules/S5131/java/how-to-fix-it/spring.adoc
Labels: java, appsec

#3639 Modify rule S3776: Ignore nested functions and default value patterns
  rules/S3776/javascript/rule.adoc
Labels: jsts

#3643 Modify rule S2004: Increase default threshold to four nested functions
  rules/S2004/javascript/rule.adoc
Labels: jsts

#3679 Use `common/` folder for ASCIIdoc parts shared between languages
  rules/S6827/common/rule.adoc
  rules/S6827/html/rule.adoc
  rules/S6827/javascript/rule.adoc
  rules/S6841/common/how.adoc
  rules/S6841/common/resources.adoc
  rules/S6841/common/why.adoc
  rules/S6841/html/rule.adoc
  rules/S6841/javascript/rule.adoc
  rules/S6846/common/resources.adoc
  rules/S6846/common/why.adoc
  rules/S6846/html/rule.adoc
  rules/S6846/javascript/rule.adoc
  rules/S6850/common/rule.adoc
  rules/S6850/html/rule.adoc
  rules/S6850/javascript/rule.adoc
  rules/S6851/common/how.adoc
  rules/S6851/common/resources.adoc
  rules/S6851/common/why.adoc
  rules/S6851/html/rule.adoc
  rules/S6851/javascript/rule.adoc
  rules/S6853/common/rule.adoc
  rules/S6853/html/rule.adoc
  rules/S6853/javascript/rule.adoc
Labels: html

#3686 Modify rule S1192: promote C# and VB to SonarWay
  rules/S1192/csharp/metadata.json
  rules/S1192/csharp/rule.adoc
  rules/S1192/exceptions-dotnet.adoc
  rules/S1192/rspecator-dotnet.adoc
  rules/S1192/vbnet/metadata.json
  rules/S1192/vbnet/rule.adoc
Labels: dotnet

#3694 Modify rule S1994: promote C# to SonarWay
  rules/S1994/csharp/metadata.json
  rules/S1994/csharp/rule.adoc
  rules/S1994/rspecator.adoc
Labels: dotnet

#3698 Modify rule S2955: promote C# to SonarWay
  rules/S2955/csharp/metadata.json
  rules/S2955/csharp/rule.adoc
  rules/S2955/metadata.json
  rules/S2955/rspecator.adoc
Labels: dotnet

#3699 Move dotnet keywords to shared_content
  rules/S4586/csharp/rule.adoc
  rules/S4586/vbnet/rule.adoc
  shared_content/dotnet/csharp_dictionary.adoc
  shared_content/dotnet/vbnet_dictionary.adoc
Labels: dotnet

#3678 Modify rule S4426: Add how to fix it for cryptodome and pyOpenSSL and close gap with NIST
  docs/header_names/allowed_framework_names.adoc
  rules/S4426/common/fix/ec.adoc
  rules/S4426/common/fix/fix.adoc
  rules/S4426/common/resources/docs.adoc
  rules/S4426/python/how-to-fix-it/pyOpenSSL.adoc
  rules/S4426/python/how-to-fix-it/pyca.adoc
  rules/S4426/python/how-to-fix-it/pycryptodome.adoc
  rules/S4426/python/rule.adoc
Labels: python

#3411 Modify rule S4830: Add HTTPX support (APPSEC-1259)
  rules/S4830/python/how-to-fix-it/httpx.adoc
  rules/S4830/python/rule.adoc
Labels: appsec, python

#3688 Modify rule S4423: Adjust Python compliant examples (APPSEC-1556)
  rules/S4423/python/how-to-fix-it/openssl.adoc
  rules/S4423/python/how-to-fix-it/ssl.adoc
Labels: appsec, python

#3708 Clean up allowed Python framework names
  docs/header_names/allowed_framework_names.adoc
Labels: python, rspec system

#3709 Modify S5344: Re-arrange the folder for new languages
  rules/S5344/common/fix/password-hashing.adoc
  rules/S5344/common/fix/plaintext-password.adoc
  rules/S5344/common/resources/standards.adoc
  rules/S5344/impact.adoc
  rules/S5344/java/rule.adoc
  rules/S5344/rationale.adoc
  rules/S5344/summary.adoc
Labels: java
