Repository SonarSource/rspec, pull requests merged in 2024-01, with the labels that each got.

#3527 Modify rule S5131: Fix Flask example (APPSEC-448)
  rules/S5131/python/how-to-fix-it/flask.adoc
Labels: appsec, python

#3531 Benchmarks Guide: Update statistical term links
  docs/benchmarks.adoc
Labels: rspec system

#3530 Modify rules S6602,S6603,S6605,S6607,S6608,S6609: Fix benchmark table
  rules/S6602/resources-dotnet.adoc
  rules/S6603/resources-dotnet.adoc
  rules/S6605/resources-dotnet.adoc
  rules/S6607/resources-dotnet.adoc
  rules/S6608/resources-dotnet.adoc
  rules/S6609/resources-dotnet.adoc
Labels: dotnet

#3506 Modify rule S1001 Literals namespaces should be allowlisted from the rule (CPP-4873)
  rules/S1001/cfamily/rule.adoc
Labels: cfamily

#3548 Modify rule S1126: Use the terms "truthy" and "falsy"
  rules/S1126/javascript/rule.adoc
Labels: jsts

#3549 Modify rule S6620: Add case for link in code font
  rules/S6620/description.adoc
Labels: rspec system

#3550 Modify JVM Crypto rules: Change framework name
  docs/header_names/allowed_framework_names.adoc
  rules/S3329/java/how-to-fix-it/java-cryptography-extension.adoc
  rules/S3329/java/rule.adoc
  rules/S3329/kotlin/how-to-fix-it/java-cryptography-extension.adoc
  rules/S3329/kotlin/rule.adoc
  rules/S4423/java/how-to-fix-it/java-cryptography-extension.adoc
  rules/S4423/java/rule.adoc
  rules/S4423/kotlin/how-to-fix-it/java-cryptography-extension.adoc
  rules/S4423/kotlin/rule.adoc
  rules/S4426/java/how-to-fix-it/java-cryptography-extension.adoc
  rules/S4426/java/rule.adoc
  rules/S4426/kotlin/how-to-fix-it/java-cryptography-extension.adoc
  rules/S4426/kotlin/rule.adoc
  rules/S4830/java/how-to-fix-it/java-cryptography-extension.adoc
  rules/S4830/java/rule.adoc
  rules/S4830/kotlin/how-to-fix-it/java-cryptography-extension.adoc
  rules/S4830/kotlin/rule.adoc
  rules/S5542/java/how-to-fix-it/java-cryptography-extension.adoc
  rules/S5542/java/rule.adoc
  rules/S5542/kotlin/how-to-fix-it/java-cryptography-extension.adoc
  rules/S5542/kotlin/rule.adoc
  rules/S5547/java/how-to-fix-it/java-cryptography-extension.adoc
  rules/S5547/java/rule.adoc
  rules/S5547/kotlin/how-to-fix-it/java-cryptography-extension.adoc
  rules/S5547/kotlin/rule.adoc
Labels: java, kotlin

#3552 Modify rule S1126: Fix code example
  rules/S4027/csharp/rule.adoc
Labels: dotnet

#3553 Modify S6473: Fix indentation
  rules/S6473/kubernetes/rule.adoc
Labels: iac

#3482 Modify Rule S2699: Fix Typos
  rules/S2699/csharp/rule.adoc
Labels: dotnet

#3528 Modify rule S6504: Clarify intention of rule (APPSEC-1350)
  rules/S6504/docker/rule.adoc
  rules/S6504/metadata.json
Labels: appsec

#3576 Modify rule S2871: Emphasize the necessity of using String.localeCompare to sort arrays of strings
  rules/S2871/javascript/rule.adoc
Labels: jsts
