Repository SonarSource/rspec, pull requests merged in 2024-07, with the labels that each got.

#4019 Modify S3247: Improve description and update example
  rules/S3247/csharp/rule.adoc
  rules/S3247/rspecator.adoc
Labels: dotnet

#4011 BUILD-4733: Use vault secrets instead of github
  .github/workflows/update_coverage.yml
Labels: common

#4027 Modify rule S5259: Document #pragma once (CPP-5133)
  rules/S5259/cfamily/metadata.json
  rules/S5259/cfamily/rule.adoc
Labels: cfamily

#4028 Modify rule S824: Clarify the most vexing parse (CPP-5122)
  rules/S824/cfamily/rule.adoc
Labels: cfamily

#4022 Modify rule S955: Mention // (CPP-5129)
  rules/S955/cfamily/metadata.json
  rules/S955/cfamily/rule.adoc
Labels: cfamily

#4033 Modify rule S117: Fix incorrect example for Kubernetes
  rules/S117/kubernetes/rule.adoc
Labels: iac

#4035 BUILD-4733: update clone command to use a github access-token
  rspec-tools/rspec_tools/coverage.py
Labels: common

#4036 BUILD-4733: Use the correct url format for cloning with an access token
  rspec-tools/rspec_tools/coverage.py
Labels: rspec system

#4039 BUILD-4733: Use COVERAGE_GITHUB_TOKEN from the vault instead of the default GITHUB_TOKEN
  .cirrus.yml
  .github/workflows/add_language.yml
  .github/workflows/create_new_rspec.yml
  .github/workflows/main.yml
  .github/workflows/update_coverage.yml
  .github/workflows/update_quickfix_status.yml
  frontend/README.adoc
  frontend/src/deployment/pullRequestIndexing.ts
  rspec-tools/rspec_tools/cli.py
  rspec-tools/rspec_tools/coverage.py
  rspec-tools/tests/test_cli.py
Labels: rspec system, common

#4044 BUILD-5580: add missing pages:write permission to Build and Deploy work
  .github/workflows/main.yml
Labels: rspec system

#4047 Modify rule S6992/S6999: Add missing variables (APPSEC-1885)
  rspec-tools/rspec_template/single_language/secrets/rule.adoc
  rules/S6992/secrets/rule.adoc
  rules/S6999/secrets/rule.adoc
Labels: secrets

#4020 RULEAPI-809 Add a new language identifier for Dart
  frontend/src/RulePage.tsx
  frontend/src/utils/useRuleCoverage.ts
  rspec-tools/rspec_tools/utils.py
  supported_languages.adoc
Labels: dart

#4049 Fix language in rule creation script
  rspec-tools/rspec_tools/create_rule.py
  rspec-tools/tests/test_create_rule.py
Labels: rspec system

#3885 Modify S3649: Add context specific code examples for Spring Data Cassandra (APPSEC-1566)
  docs/header_names/allowed_framework_names.adoc
  rules/S3649/java/how-to-fix-it/cassandra.adoc
  rules/S3649/java/rule.adoc
Labels: java, appsec

#3911 Modify rule S3649: Add Neo4j example
  docs/header_names/allowed_framework_names.adoc
  rules/S3649/java/how-to-fix-it/spring-data-neo4j.adoc
  rules/S3649/java/rule.adoc
Labels: java

#3912 Modify S5147: Add context specific code examples for Spring Data MongoDB
  docs/header_names/allowed_framework_names.adoc
  rules/S5147/java/how-to-fix-it/spring-data-mongodb.adoc
  rules/S5147/java/rule.adoc
Labels: java, appsec

#3897 Modify rule S3649: Add Couchbase example
  docs/header_names/allowed_framework_names.adoc
  rules/S3649/java/how-to-fix-it/couchbase.adoc
  rules/S3649/java/rule.adoc
Labels: java

#4050 Modify rule S841 Update with the specification from M23_154 (CPP-5136)
  rules/S841/cfamily/metadata.json
  rules/S841/cfamily/rule.adoc
Labels: cfamily

#4052 Modify S2699: Add Moq as a valid assertions framework
  rules/S2699/csharp/rule.adoc
Labels: dotnet

#4042 Modify rule S6200 Don't allow local volatile variables (M23_387) (CPP-5140)
  rules/S3687/cfamily/metadata.json
  rules/S3687/cfamily/rule.adoc
  rules/S6200/cfamily/rule.adoc
Labels: cfamily

#4058 Modify rule S6893 Ensure whitespace in-between braces
  rules/S6893/kubernetes/rule.adoc
Labels: iac

#4060 Modify rule S121: activate in Dart by default
  rules/S121/dart/metadata.json
Labels: dart

#3857 Modify rule S6398: Add How to fix it in Spring
  rules/S6398/java/how-to-fix-it/spring.adoc
  rules/S6398/java/rule.adoc
Labels: appsec

#4081 BUILD-4175 Fix permission issue when canceling the update coverage action
  .github/workflows/update_coverage.yml
Labels: rspec system

#4082 Update rule S7028: change example and implementation details
  rules/S7028/docker/rule.adoc
Labels: iac

#4085 Modify rule S6587: Describe a soltuion with a cache mount
  rules/S6587/docker/rule.adoc
Labels: iac

#4089 Fix coverage script when there is no new coverage
  .github/workflows/update_coverage.yml
Labels: rspec system

#4090 Modify S3168: Fix error in compliant code example
  rules/S3168/csharp/rule.adoc
Labels: dotnet

#4091 Modify rule S7021: improve text
  rules/S7021/docker/rule.adoc
Labels: iac

#4093 Modify rules S6994,S6996: add missing since-c++11 tags
  rules/S6994/cfamily/metadata.json
  rules/S6996/cfamily/metadata.json
Labels: cfamily

#4095 Modify rule S7018: change title, make applicable for single-line instructions
  rules/S7018/docker/metadata.json
  rules/S7018/docker/rule.adoc
Labels: iac
