Repository SonarSource/rspec, pull requests merged in 2024-05, with the labels that each got.

#3920 Modify S6960: Fix typo
  rules/S6960/csharp/rule.adoc
  rules/S6964/S6964_csharp.cs
  rules/S6966/S6966_csharp.cs
  rules/S6967/S6967_csharp.cs
  rules/S6968/csharp/Testcases/S6968.cs
  rules/S6968/csharp/Testcases/Snippets.cs
Labels: dotnet

#3921 Modify rule S2529: Fix encoding issue in PL/SQL
  rules/S2529/plsql/rule.adoc
Labels: plsql

#3923 Modify S2365: Fix code examples
  rules/S2365/csharp/rule.adoc
  rules/S2365/vbnet/rule.adoc
Labels: dotnet

#3924 Modify rule S3358 for JS: clarify exception
  rules/S3358/javascript/rule.adoc
Labels: jsts

#3926 Modify rule S6962: Fix rule link
  rules/S6962/csharp/rule.adoc
Labels: dotnet

#3927 Modify rule S5786: Fix rule link
  rules/S5786/java/rule.adoc
Labels: java

#3925 CPP-5096 S1236 Explain covered cases and exception
  rules/S1236/cfamily/metadata.json
  rules/S1236/cfamily/rule.adoc
Labels: cfamily

#3928 Forbid adding a link to rules.sonarsource.com
  rspec-tools/Pipfile
  rspec-tools/rspec_tools/validation/sanitize_asciidoc.py
  rspec-tools/tests/resources/invalid-asciidoc/link_rule_sonarsource_com.adoc
  rspec-tools/tests/resources/invalid-asciidoc/snapshots/include_stuck_after.txt
  rspec-tools/tests/resources/invalid-asciidoc/snapshots/include_stuck_before.txt
  rspec-tools/tests/resources/invalid-asciidoc/snapshots/link_rule_sonarsource_com.txt
  rspec-tools/tests/resources/invalid-asciidoc/snapshots/two_stuck_includes.txt
  rspec-tools/tests/resources/invalid-asciidoc/snapshots/unnamed_language.txt
  rspec-tools/tests/validation/test_asciidoc_sanitization.py
  rules/S2583/comments-and-links.adoc
Labels: rspec system

#3930 Rule S6781: Remove redundant code from net-core snippet
  rules/S6781/csharp/how-to-fix/net-core.adoc
Labels: dotnet

#3932 Modify rule S104, S138, S1151, S1752, S1753: Adapt titles and messages
  rules/S104/rpg/metadata.json
  rules/S104/rpg/rule.adoc
  rules/S1151/rpg/metadata.json
  rules/S1151/rpg/rule.adoc
  rules/S138/rpg/metadata.json
  rules/S1752/rpg/rule.adoc
  rules/S1753/rpg/rule.adoc
Labels: rpg

#3934 Modify rule S1871: remove rpg exception
  rules/S1871/rpg/exceptions.adoc
Labels: rpg

#3931 S5344: Fix typo
  rules/S5344/csharp/message.adoc
Labels: dotnet

#3935 Modify rule S6974: Don't reference an unimplemented rule
  rules/S6974/python/rule.adoc
Labels: python

#3936 Minor cleanup/refactoring on S5344 for C# and Python
  rules/S5344/csharp/highlighting.adoc
  rules/S5344/csharp/message.adoc
  rules/S5344/python/message.adoc
Labels: python, dotnet

#3937 S5344: Fix 2**12 -> 2^12
  rules/S5344/common/fix/bcrypt-parameters.adoc
Labels: java, python, dotnet, xml

#2520 Modify rule S4423: Remove instructions that are not relevant for API Gateway V2 (APPSEC-182)
  rules/S4423/cloudformation/how-to-fix-it/api-gateway.adoc
  rules/S4423/cloudformation/rule.adoc
Labels: iac

#3938 Modify rule S5421: Update RSPEC and add exception for volatile
  rules/S5421/cfamily/rule.adoc
Labels: cfamily

#2676 Modify rule S4423: Add "How to fix" sections for all Azure resources (APPSEC-383)
  docs/header_names/allowed_framework_names.adoc
  rules/S4423/terraform/how-to-fix-it/azure-databases.adoc
  rules/S4423/terraform/how-to-fix-it/azure-mssql.adoc
  rules/S4423/terraform/how-to-fix-it/azure-storage-account.adoc
  rules/S4423/terraform/rule.adoc
Labels: appsec, security, iac

#3933 Modify rule S5500: mention std::ranges::move and rewrite RSPEC (CPP-5219)
  rules/S5500/cfamily/metadata.json
  rules/S5500/cfamily/rule.adoc
Labels: cfamily

#3946 Modify S2221: Improve compliant example
  rules/S2221/csharp/rule.adoc
Labels: dotnet

#3944 Deprecate rule S6869
  rules/S6869/kubernetes/metadata.json
Labels: iac

#3943 Update S6273: Re-organize and simplify description
  rules/S6273/cloudformation/rule.adoc
  rules/S6273/description.adoc
  rules/S6273/see.adoc
  rules/S6273/summary.adoc
Labels: iac

#3942 Modify rule S6964: Update message and description
  rules/S6964/csharp/rule.adoc
  rules/S6964/metadata.json
Labels: dotnet

#3939 Modify rule S3539: Make the rule accept redundant specifiers when one is for functions, the other for variables (CPP-5221)
  rules/S3539/cfamily/rule.adoc
Labels: cfamily

#3945 Update rule S6931: Remove VB deprecation
  rules/S6931/vbnet/metadata.json
Labels: dotnet

#3940 Modify rule S6945: fix typo in title
  rules/S6945/jcl/metadata.json
Labels: jcl

#3948 Modify rule S6964: Add more entries to the exceptions
  rules/S6964/csharp/rule.adoc
Labels: dotnet

#3947 Modify rule S6946: change CCT attribute
  rules/S6946/jcl/metadata.json
Labels: jcl

#3950 Modify rules S6962, S6966: Add asp.net tag
  rules/S6932/S6932.AspNet4x.cs
  rules/S6932/S6932.AspNetCore.cs
  rules/S6962/csharp/metadata.json
  rules/S6966/metadata.json
Labels: dotnet

#3952 Insert space in nocompliant comments
  rules/S1244/csharp/rule.adoc
  rules/S1694/csharp/rule.adoc
  rules/S3221/rule.adoc
  rules/S3254/rule.adoc
  rules/S3264/csharp/rule.adoc
  rules/S3955/rule.adoc
  rules/S5344/csharp/how-to-fix-it/aspnetframework.adoc
  rules/S6962/csharp/rule.adoc
Labels: dotnet

#3898 Modify rule S1265: Add support for sized delete (M23_358) and globally improve the rule (CPP-5138 CPP-1313 )
  rules/S1265/cfamily/metadata.json
  rules/S1265/cfamily/rule.adoc
Labels: cfamily
