Repository SonarSource/rspec, pull requests merged in 2025-04, with the labels that each got.

#4880 Upgrade Python to 3.12 to fix tooling tests
  ci/Dockerfile
  ci/install_rspec_tools_dependencies.sh
  rspec-tools/Pipfile
  rspec-tools/Pipfile.lock
  rspec-tools/tests/__init__.py
  rspec-tools/tests/validation/test_metadata_validation.py
Labels: rspec system

#4864 SONARJAVA-5403 Modify rule S7435: set quickfix for all languages
  rules/S7435/metadata.json
Labels: java, appsec, kotlin

#4878 SONARJAVA-5403 Modify rule S7435: fix missing semicolon in code example
  rules/S7435/java/rule.adoc
Labels: java, appsec

#4882 JS-676 Update mapping for js/ts files
  rspec-tools/rspec_tools/coverage.py
  rspec-tools/tests/test_coverage.py
Labels: javascript

#4866 SONARJAVA-5420 Modify rule S5344: set quickfix for Java and Kotlin
  rules/S5344/java/metadata.json
  rules/S5344/kotlin/metadata.json
Labels: java, appsec, kotlin

#4822 Modify S5344: Add JCE code example for Java (SONARKT-582)
  rules/S5344/java/how-to-fix-it/java-cryptography-extension.adoc
  rules/S5344/java/how-to-fix-it/spring.adoc
  rules/S5344/java/rule.adoc
Labels: java

#4924 Modify rule S110: Added architecture tag
  rules/S110/metadata.json
Labels: architecture

#4926 Modify rule S1200: Added architecture & design tags
  rules/S1200/metadata.json
Labels: architecture

#4927 Modify rule S138: Added architecture & design tags
  rules/S138/metadata.json
Labels: architecture

#4930 Modify rule S1448: Added architecture & design tags
  rules/S1448/metadata.json
Labels: architecture

#4933 Modify rule S3776: Added architecture & design tags
  rules/S3776/metadata.json
Labels: architecture

#4934 Modify rule S6627: Added architecture & design tags
  rules/S6627/metadata.json
Labels: architecture

#4935 Modify rule S6861: Added architecture & design tags
  rules/S6861/javascript/metadata.json
Labels: architecture

#4938 Modify rule S104: Consolidate on architecture tag. Design tag not nee…
  rules/S104/metadata.json
Labels: architecture

#4939 Modify rule S1200: Consolidate on architecture tag. Design tag not ne…
  rules/S1200/metadata.json
Labels: architecture

#4940 Modify rule S110: Consolidate on architecture tag. Design tag not nee…
  rules/S110/metadata.json
Labels: architecture

#4941 Modify rule S138: Consolidate on architecture tag. Design tag not nee…
  rules/S138/metadata.json
Labels: architecture

#4942 Modify rule S1448: Consolidate on architecture tag. Design tag not ne…
  rules/S1448/metadata.json
Labels: architecture

#4945 Modify rule S2972: Consolidate on architecture tag. Design tag not ne…
  rules/S2972/java/metadata.json
Labels: architecture

#4946 Modify rule S3776: Consolidate on architecture tag. Design tag not ne…
  rules/S3776/metadata.json
Labels: architecture

#4947 Modify rule S6627: Consolidate on architecture tag. Design tag not ne…
  rules/S6627/metadata.json
Labels: architecture

#4948 Modify rule S6861: Consolidate on architecture tag. Design tag not ne…
  rules/S6861/javascript/metadata.json
Labels: architecture

#4949 Modify rule S7060: Consolidate on architecture tag. Design tag not ne…
  rules/S7060/javascript/metadata.json
Labels: architecture

#4889 Refresh rspec-tools to fix tests when run locally
  rspec-tools/Pipfile
  rspec-tools/Pipfile.lock
  rspec-tools/README.adoc
  rspec-tools/rspec_tools/checklinks.py
  rspec-tools/rspec_tools/utils.py
  rspec-tools/rspec_tools/validation/description.py
  rspec-tools/tests/conftest.py
  rspec-tools/tests/links/__init__.py
  rspec-tools/tests/links/test_links.py
  rspec-tools/tests/test_coverage.py
  rspec-tools/tests/validation/__init__.py
Labels: rspec system

#4890 Batch-reformat rspec-tools to follow the python conventions and enforce code style in CI
  .cirrus.yml
  rspec-tools/Pipfile
  rspec-tools/Pipfile.lock
  rspec-tools/README.adoc
  rspec-tools/rspec_tools/__init__.py
  rspec-tools/rspec_tools/checklinks.py
  rspec-tools/rspec_tools/cli.py
  rspec-tools/rspec_tools/coverage.py
  rspec-tools/rspec_tools/create_rule.py
  rspec-tools/rspec_tools/errors.py
  rspec-tools/rspec_tools/modify_rule.py
  rspec-tools/rspec_tools/notify_failure_on_slack.py
  rspec-tools/rspec_tools/repo.py
  rspec-tools/rspec_tools/rules.py
  rspec-tools/rspec_tools/utils.py
  rspec-tools/rspec_tools/validation/description.py
  rspec-tools/rspec_tools/validation/metadata.py
  rspec-tools/rspec_tools/validation/sanitize_asciidoc.py
  rspec-tools/tests/conftest.py
  rspec-tools/tests/links/test_links.py
  rspec-tools/tests/test_cli.py
  rspec-tools/tests/test_coverage.py
  rspec-tools/tests/test_create_rule.py
  rspec-tools/tests/test_modify_rule.py
  rspec-tools/tests/test_repo.py
  rspec-tools/tests/test_rules_repository.py
  rspec-tools/tests/test_utils.py
  rspec-tools/tests/validation/test_description_validation.py
  rspec-tools/tests/validation/test_metadata_validation.py
  rspec-tools/tox.ini
Labels: rspec system

#4951 SONARJAVA-5476 Modify rule S1217: Fix broken link
  rules/S1217/java/rule.adoc
Labels: java

#4953 Modify rule S1313: Fix link to HTTP page
  rules/S1313/abap/rule.adoc
  rules/S1313/apex/rule.adoc
  rules/S1313/cfamily/rule.adoc
  rules/S1313/csharp/rule.adoc
  rules/S1313/go/rule.adoc
  rules/S1313/java/rule.adoc
  rules/S1313/javascript/rule.adoc
  rules/S1313/kotlin/rule.adoc
  rules/S1313/php/rule.adoc
  rules/S1313/python/rule.adoc
  rules/S1313/ruby/rule.adoc
  rules/S1313/scala/rule.adoc
  rules/S1313/tsql/rule.adoc
  rules/S1313/vb6/rule.adoc
  rules/S1313/vbnet/rule.adoc
Labels: appsec

#4903 Refactor and expand tests for check-links
  ci/validate_links.sh
  rspec-tools/rspec_tools/checklinks.py
  rspec-tools/rspec_tools/cli.py
  rspec-tools/tests/links/404/S100/java/rule.html
  rspec-tools/tests/links/OK/S100/java/rule.html
  rspec-tools/tests/links/URL/S100/java/rule.html
  rspec-tools/tests/links/__init__.py
  rspec-tools/tests/links/deprecated/S100/java/metadata.json
  rspec-tools/tests/links/deprecated/S100/java/rule.html
  rspec-tools/tests/links/deprecated/S100/metadata.json
  rspec-tools/tests/links/deprecated/S100/rpg/metadata.json
  rspec-tools/tests/links/deprecated/S100/rpg/rule.html
  rspec-tools/tests/links/test_links.py
  rspec-tools/tests/test_links.py
Labels: rspec system

#4955 SONARJAVA-5476 Modify rule S5332: Update link to JSch library to a replacement
  rules/S5332/java/rule.adoc
  rules/S5332/kotlin/rule.adoc
Labels: java

#4954 SONARJAVA-5476 Modify rule S6363: Disable a url not meant to be a documentation link
  rules/S6363/kotlin/rule.adoc
Labels: java

#4888 Ignore baeldung.com links in the link checker
  rspec-tools/rspec_tools/checklinks.py
  rspec-tools/tests/test_links.py
Labels: rspec system

#4963 SONARTEXT-350 Modify rule S7203: Fix typos
  rules/S7203/secrets/rule.adoc
  shared_content/secrets/fix/store_separately.adoc
  shared_content/secrets/fix/store_separatly.adoc
  shared_content/secrets/impact/private_key_disclosure.adoc
Labels: secrets

#4964 Modify rule S3236: Add rule exception
  rules/S3236/rule.adoc
Labels: dotnet

#4950 SONARJAVA-5410 Modify rule S5977: Improve Rationale for Avoiding Randomness in Tests
  rules/S5977/java/rule.adoc
Labels: java

#4965 DART-245 Modify rule S7088: Make it a vulnerability
  rules/S7088/dart/metadata.json
  rules/S7088/dart/rule.adoc
Labels: appsec, dart

#4971 JS-72 S6767: Update rspec with FP explanation
  rules/S6767/javascript/rule.adoc
Labels: javascript

#4967 Modify rule S6649: Add exceptions for x / 0
  rules/S6649/java/rule.adoc
Labels: java

#4976 NET-1349 Modify S3267: Mention IAsyncEnumerable
  rules/S3267/csharp/rule.adoc
Labels: dotnet

#4977 NET-1348 Modify S1699: Add How to fix it section
  rules/S1699/csharp/rule.adoc
Labels: dotnet

#4975 SONARJAVA-5517 Modify S1481: add information about the java unnamed pattern
  rules/S1481/java/metadata.json
  rules/S1481/java/rule.adoc
Labels: java

#4958 Update Python version for coverage update
  .github/workflows/update_coverage.yml
  rspec-tools/Pipfile.lock
Labels: rspec system
