Repository SonarSource/rspec, pull requests merged in 2025-01, with the labels that each got.

#4590 S6018 Add example showing use of `inline` out of line (CPP-4342)
  rules/S6018/cfamily/rule.adoc
Labels: cfamily

#4592 NET-933 Modify S1155: Add benchmarks
  rules/S1155/csharp/rule.adoc
Labels: dotnet

#4595 Modify S3169: Add benchmarks
  rules/S3169/csharp/rule.adoc
  rules/S6961/csharp/metadata.json
Labels: dotnet

#4600 NET-934 Modify S1643: Use NetFx 4.8.1 in Brenchmark
  rules/S1643/csharp/rule.adoc
Labels: dotnet

#4597 SONARIAC-1856 Modify S7019: add EXEC alternatives and exceptions
  rules/S7019/docker/rule.adoc
Labels: iac

#4601 NET-943 Modify rule S1215: Add benchmark
  rules/S1215/csharp/rule.adoc
Labels: dotnet

#4602 NET-938 Modify S2629: Add benchmarks
  rules/S2629/csharp/rule.adoc
Labels: dotnet

#4584 Add PullRequesteCreated.yml
  .github/pull_request_template.md
  .github/workflows/PullRequestCreated.yml
Labels: rspec system

#4596 NET-936 Modify S3247: Add benchmarks
  rules/S3247/csharp/rule.adoc
Labels: dotnet

#4605 Modify rule S6961: Add perftag back
  rules/S6961/csharp/metadata.json
Labels: dotnet

#4606 SONARIAC-1856 Modify S7019: remove second example id/diff
  rules/S7019/docker/rule.adoc
Labels: iac

#4608 NET-915 Modify S2930: Fix typo
  rules/S2930/csharp/rule.adoc
Labels: dotnet

#4604 SONARIAC-1892 Modify rule S6975: Fix how to fix it section split
  docs/header_names/allowed_framework_names.adoc
  rules/S117/azureresourcemanager/rule.adoc
  rules/S1192/azureresourcemanager/rule.adoc
  rules/S1481/azureresourcemanager/rule.adoc
  rules/S6321/azureresourcemanager/how-to-fix-it/bicep.adoc
  rules/S6321/azureresourcemanager/how-to-fix-it/json.adoc
  rules/S6321/azureresourcemanager/rule.adoc
  rules/S6378/azureresourcemanager/rule.adoc
  rules/S6385/azureresourcemanager/how-to-fix-it/bicep.adoc
  rules/S6385/azureresourcemanager/how-to-fix-it/json.adoc
  rules/S6385/azureresourcemanager/rule.adoc
  rules/S6437/azureresourcemanager/rule.adoc
  rules/S6648/azureresourcemanager/how-to-fix-it/json.adoc
  rules/S6648/azureresourcemanager/rule.adoc
  rules/S6656/azureresourcemanager/how-to-fix-it/json.adoc
  rules/S6656/azureresourcemanager/rule.adoc
  rules/S6874/azureresourcemanager/rule.adoc
  rules/S6949/azureresourcemanager/rule.adoc
  rules/S6952/azureresourcemanager/rule.adoc
  rules/S6953/azureresourcemanager/rule.adoc
  rules/S6954/azureresourcemanager/rule.adoc
  rules/S6955/azureresourcemanager/rule.adoc
  rules/S6956/azureresourcemanager/how-to-fix-it/bicep.adoc
  rules/S6956/azureresourcemanager/how-to-fix-it/json.adoc
  rules/S6956/azureresourcemanager/rule.adoc
  rules/S6975/azureresourcemanager/how-to-fix-it/bicep.adoc
  rules/S6975/azureresourcemanager/how-to-fix-it/json.adoc
  rules/S6975/azureresourcemanager/rule.adoc
Labels: iac

#4609 NET-988 Remove S1197 from SonarWay for VB.NET
  rules/S1197/vbnet/metadata.json
Labels: dotnet

#4603 Apply missing `android` tags to rules that support Android APIs (APPSEC-2374)
  rules/S3649/java/metadata.json
  rules/S5332/java/metadata.json
  rules/S5332/kotlin/metadata.json
  rules/S5332/xml/metadata.json
  rules/S6293/metadata.json
Labels: appsec

#2770 Modify rule S3330: Add Go language
  rules/S3330/go/metadata.json
  rules/S3330/go/rule.adoc
Labels: go

#4623 SONARJAVA-5291 Modify rule S7177: specify spring context
  rules/S7177/java/rule.adoc
Labels: java

#2760 Modify rule S2092: Add Go language
  rules/S2092/go/metadata.json
  rules/S2092/go/rule.adoc
Labels: go

#4619 SONARJAVA-5293 Modify rule S6856 to also cover opposite case
  rules/S6856/java/rule.adoc
Labels: java

#4621 NET-1038 Add symbolic-execution tag to our rules
  rules/S2053/csharp/metadata.json
  rules/S2053/vbnet/metadata.json
  rules/S2222/java/metadata.json
  rules/S2222/metadata.json
  rules/S2259/csharp/metadata.json
  rules/S2259/vbnet/metadata.json
  rules/S2583/csharp/metadata.json
  rules/S2583/vbnet/metadata.json
  rules/S2589/csharp/metadata.json
  rules/S2589/vbnet/metadata.json
  rules/S3329/csharp/metadata.json
  rules/S3329/vbnet/metadata.json
  rules/S3655/java/metadata.json
  rules/S3655/metadata.json
  rules/S3900/metadata.json
  rules/S3949/metadata.json
  rules/S3966/metadata.json
  rules/S4158/csharp/metadata.json
  rules/S4158/vbnet/metadata.json
  rules/S4347/csharp/metadata.json
  rules/S5773/metadata.json
  rules/S6781/csharp/metadata.json
  rules/S7130/metadata.json
  rules/S7131/metadata.json
  rules/S7133/metadata.json
Labels: dotnet

#4626 SONARJAVA-5295 Modify rule S6809: add support for @Cacheable
  rules/S6809/java/rule.adoc
Labels: java

#4628 SONARGO-175 ParsingError should be disabled by default
  rules/S2260/go/metadata.json
Labels: go

#4630 Update GitHub CODEOWNERS
  .github/CODEOWNERS
Labels: rspec system

#4635 [NO-JIRA] Point coverage script to the enterprise sonar-go repository
  rspec-tools/rspec_tools/coverage.py
Labels: go

#4644 Modify rule S4487: Fix error in code example
  rules/S4487/csharp/rule.adoc
Labels: dotnet

#4643 SONARJAVA-5285 Modify rule S7180: update wrong rule description
  rules/S7180/java/rule.adoc
Labels: java
